vpa:
  admissionController:
    enabled: false
  updater:
    enabled: false
  recommender:
    enabled: true
    extraArgs:
      pod-recommendation-min-cpu-millicores: 15
      pod-recommendation-min-memory-mb: 16
      storage: prometheus
      prometheus-address: |
        http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
