loki:
  test:
    enabled: false
  lokiCanary:
    enabled: false
  deploymentMode: SingleBinary
  singleBinary:
    replicas: 1
  read:
    replicas: 0
  backend:
    replicas: 0
  write:
    replicas: 0
  gateway:
    enabled: false
  ingress:
    enabled: false
  serviceAccount:
    create: true
  loki:
    storage:
      type: s3
      s3:
        region: eu-central-1
    schemaConfig:
      configs:
        - from: 2024-04-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h
  # loki needs explicit configuration
  # https://grafana.com/docs/loki/latest/operations/caching/
  chunksCache:
    enabled: false
    allocatedMemory: 256
    resources:
      requests:
        cpu: 100m
        memory: 320Mi
      limits:
        cpu: 300m
        memory: 320Mi
  resultsCache:
    enabled: false
    allocatedMemory: 32
    resources:
      requests:
        cpu: 100m
        memory: 40Mi
      limits:
        cpu: 300m
        memory: 40Mi
