loki:
  test:
    enabled: false
  lokiCanary:
    enabled: false
  deploymentMode: SingleBinary
  singleBinary:
    replicas: 1
  read:
    replicas: 0
  backend:
    replicas: 0
  write:
    replicas: 0
  gateway:
    enabled: false
  ingress:
    enabled: false
  loki:
    storage:
      type: s3
    schemaConfig:
      configs:
        - from: 2024-04-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h
