loki:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::106102538874:role/loki-dev"
  loki:
    storage:
      bucketNames:
        chunks: aeternity-loki-chunks-dev
        ruler: aeternity-loki-ruler-dev
        admin: aeternity-loki-admin-dev
