aws-ebs-csi-driver:
  logLevel: debug

  node:
    enableWindows: false
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi

  controller:
    resources:
      limits:
        memory: 80Mi
      requests:
        cpu: 10m
        memory: 80Mi
        
  storageClasses:
  - name: ebs-sc
    volumeBindingMode: WaitForFirstConsumer
