app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7
    values:
      DB_PASSWORD: "/hedgedoc/DB_PASSWORD"

hedgedoc:
  image:
    repository: ghcr.io/linuxserver/hedgedoc
    pullPolicy: IfNotPresent
    tag: "version-1.9.6"
  
  secret: {}
    # DB_PASS: "hedgedoc-pass"

  env:
    CMD_DOMAIN: "hedgedoc.dev.aeternity.io"
    
  service:
    port:
      port: 3000
  
  connection:
    database: 
      password: DB_PASSWORD
      databaseName: hedgedoc

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: "hedgedoc.dev.aeternity.io"
        paths:
        - path: /
          pathType: Prefix

  persistence:
    config:
      enabled: true
      emptyDir: false
      mountPath: /config
  
  mariadb:
    enabled: true
    volumePermissions:
      enabled: true
    db:
      user: hedgedoc
      password: DB_PASSWORD
      name: hedgedoc
    master:
      persistence:
        enabled: true
    replication:
      enabled: false

  authentication:
    local:
      enabled: true
      allowRegister: true
