app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7
    values:
      DB_PASS: "/hedgedoc/DB_PASSWORD"
      GITHUB_CLIENT_SECRET: "/hedgedoc/GITHUB_CLIENT_SECRET"
      GITHUB_CLIENT_ID: "/hedgedoc/GITHUB_CLIENT_ID"
      SESSION_SECRET: "/hedgedoc/SESSION_SECRET"

hedgedoc:
    # Default values for codimd.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # storageClass:
  # nameOverride:
  # fullnameOverride:

  image:
    registry: "quay.io"
    repository: "hedgedoc/hedgedoc"
    tag: "1.9.4"
    pullPolicy: IfNotPresent
    pullSecrets: []
  #    - myRegistryKeySecretName

  mariadb:
    enabled: false
    volumePermissions:
      enabled: true
    db:
      user: hedgedoc
      password: changeme
      name: hedgedoc
    master:
      persistence:
        enabled: true
    replication:
      enabled: false

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: "hedgedoc.dev.aeternity.io"
        paths:
        - path: /
          pathType: Prefix 
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


  ##
  ## HedgeDoc application configuration
  ##
  hedgedoc:
    connection:
      ## if you doesn't using ingress, you can setup domain for your CodiMD instances
      domain: hedgedoc.dev.aeternity.io
      ## if you want to add port number on your url
      urlAddPort: false
      ## if you use load balancer or setup TLS on ingress
      protocolUseSSL: false

    ##
    ## External database configuration
    ##   if you want to use external database
    ##   database type only support mysql and postgres
    ##
    #  database:
    #    type: postgres
    #    host:
    #    port:
    #    username:
    #    password:
    #    databaseName:
    imageStorePersistentVolume:
      enabled: true
      size: '10Gi'
      storageClass: "-"
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem

    ## for advanced used, manually setup environment for used
    extraEnvironmentVariables:
       CMD_LOGLEVEL: debug

    ## automatically check new version
    versionCheck: true

    ##
    ## about security setting
    ##
    security:
      useCDN: 'false'
      # session secret, please change this value
      sessionSecret: 'changeit'
      sessionLife: '1209600000'
      ## HSTS setting
      hstsEnabled: 'true'
      hstsMaxAge: '31536000'
      hstsIncludeSubdomain: 'false'
      hstsPreload: 'true'
      ## CSP setting
      cspEnabled: 'true'
      # cspReportUri:
      ## setup allow origin
      # allowOrigin:
      ## use gravatar.com as user gravatar
      allowGravatar: 'true'

    ##
    ## for tooBusy block user when server event loop lag more than ? ms
    ##
    responseMaxLag: '70'

    ##
    ## setting about note creation
    ##
    noteCreation:
      freeUrlEnabled: 'false'
      freeUrlForbiddenNoteIds: 'robots.txt,favicon.ico,api'
      defaultPermission: 'editable'
    ##
    ## setting about note permission
    ##
    notePermission:
      allowAnonymousEdit: true
      allowAnonymousView: true
    ##
    ## allow export note to pdf
    ##
    allowPDFExport: false
    ##
    ## setting about markdown
    ##
    markdown:
      # plantUMLServer:
      useHardBreak: true
      linkifyHeaderStyle: 'keep-case'
    authentication:
      local:
        enabled: true
        allowRegister: true
      github:
        enabled: true
        clientId: GITHUB_CLIENT_ID
        secret: GITHUB_CLIENT_SECRET
