app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7
    values:
      DB_PASSWORD: "/hedgedoc/DB_PASSWORD"
      GITHUB_CLIENT_SECRET: "/hedgedoc/GITHUB_CLIENT_SECRET"
      GITHUB_CLIENT_ID: "/hedgedoc/GITHUB_CLIENT_ID"
      SESSION_SECRET: "/hedgedoc/SESSION_SECRET"
      
hedgedoc:
  image:
    repository: ghcr.io/linuxserver/hedgedoc
    pullPolicy: IfNotPresent
    tag: "version-1.9.6"
  
  secret: {}
    # DB_PASS: "hedgedoc-pass"

  env:
    CMD_DOMAIN: "hedgedoc.dev.aeternity.io"
    DB_USER: hedgedoc
    DB_PASS: DB_PASSWORD
    DB_NAME: hedgedoc
    
  service:
    port:
      port: 3000
  
  authentication:
    github:
      enabled: true
      clientId: GITHUB_CLIENT_ID
      secret: GITHUB_CLIENT_SECRET
  
  security:
    sessionSecret: SESSION_SECRET

  connection:
    database: 
      password: DB_PASSWORD
      databaseName: hedgedoc

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: "hedgedoc.dev.aeternity.io"
        paths:
        - path: /
          pathType: Prefix

  persistence:
    config:
      enabled: true
      emptyDir: false
      mountPath: /config
  
  mariadb:
    enabled: true
    volumePermissions:
      enabled: true
    db:
      user: hedgedoc
      password: DB_PASSWORD
      name: hedgedoc
    master:
      persistence:
        enabled: true
    replication:
      enabled: false

