hedgedoc:
  image:
    repository: ghcr.io/linuxserver/hedgedoc
    pullPolicy: IfNotPresent
    tag: "version-1.9.6"
  
  secret: {}
    # DB_PASS: "hedgedoc-pass"
  
  # See more environment variables in the hedgedoc documentation
  # https://github.com/linuxserver/docker-hedgedoc#parameters
  env:
    # TZ:
    # PUID: "1000"
    # PGID: "1000"
    # DB_USER: "hedgedoc"
    # DB_HOST: "mariadb"
    # DB_NAME: "hedgedoc"
    # DB_PORT: "3306"
    CMD_DOMAIN: "hedgedoc.dev.aeternity.io"
    CMD_URL_ADDPORT: true
    CMD_PORT: 443
    CMD_PROTOCOL_USESSL: true
  
  service:
    port:
      port: 3000
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: "hedgedoc.dev.aeternity.io"
        paths:
        - path: /
          pathType: Prefix

  persistence:
    config:
      enabled: false
      emptyDir: false
      mountPath: /config
  
  # Enable mariadb
  # https://github.com/nicholaswilde/helm-charts/blob/main/charts/mariadb/values.yaml
  mariadb:
    enabled: false
    env:
      MYSQL_USER: hedgedoc
      MYSQL_DATABASE: hedgedoc
    fullnameOverride: hedgedoc-mariadb
