app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7
    values:
      WIKI_DB_PASSWORD: "/wikijs/DB_PASSWORD"
      PG_DB_PASSWORD: "/wikijs/DB_PASSWORD"

postgresql:
  ## @section Global parameters
  ## Please, note that this will override the parameters, including dependencies, configured to use the global value
  ##
  global:
    storageClass: ""
    postgresql:
      ## @param global.postgresql.auth.postgresPassword Password for the "postgres" admin user (overrides `auth.postgresPassword`)
      ## @param global.postgresql.auth.username Name for a custom user to create (overrides `auth.username`)
      ## @param global.postgresql.auth.password Password for the custom user to create (overrides `auth.password`)
      ## @param global.postgresql.auth.database Name for a custom database to create (overrides `auth.database`)
      ## @param global.postgresql.auth.existingSecret Name of existing secret to use for PostgreSQL credentials (overrides `auth.existingSecret`).
      ## @param global.postgresql.auth.secretKeys.adminPasswordKey Name of key in existing secret to use for PostgreSQL credentials (overrides `auth.secretKeys.adminPasswordKey`). Only used when `global.postgresql.auth.existingSecret` is set.
      ## @param global.postgresql.auth.secretKeys.userPasswordKey Name of key in existing secret to use for PostgreSQL credentials (overrides `auth.secretKeys.userPasswordKey`). Only used when `global.postgresql.auth.existingSecret` is set.
      ## @param global.postgresql.auth.secretKeys.replicationPasswordKey Name of key in existing secret to use for PostgreSQL credentials (overrides `auth.secretKeys.replicationPasswordKey`). Only used when `global.postgresql.auth.existingSecret` is set.
      ##
      auth:
        username: "wikijs"
        password: "WIKI_DB_PASSWORD"
        database: "wikijs"
        postgresPassword: "PG_DB_PASSWORD"
        existingSecret: "postgresql-app-secrets"
        secretKeys:
          userPasswordKey: "WIKI_DB_PASSWORD"
      
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 15.1.0-debian-11-r20
    debug: false
  auth:
    ## @param auth.enablePostgresUser Assign a password to the "postgres" admin user. Otherwise, remote access will be blocked for this user
    ##
    enablePostgresUser: false
