{
 "title": "Kubernetes Events",
 "description": "Kubernetes Events from custom Controller",
 "tags": [
  "loki",
  "events",
  "kubernetes",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "fluentbit.k8s.events" },
   {
    "name": "cluster_name",
    "label": "cluster_name",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {}
   },
   {
    "name": "kind",
    "label": "kind",
    "query": {}
   },
   {
    "name": "type",
    "label": "type",
    "query": {}
   },
   {
    "name": "reason",
    "label": "reason",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events Timeline",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(cluster_name, namespace, pod, type) (count_over_time({job=\"$job\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", kind=~\"$kind\", reason=~\"$reason\", type=~\"$type\"} |= `` [$__interval]))"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (count_over_time({job=\"$job\"} | __error__=\"\" [$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$job\"} | type = \"Warning\" | __error__=\"\" [$__interval]))",
     "legendFormat": "Warning"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "By Kind",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$job\"}| __error__=\"\"[$__interval])) by (kind)",
     "legendFormat": "{{source_component}}"
    }
   ]
  },
  {
   "title": "By Namespace",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$job\"}| __error__=\"\"[$__interval])) by (namespace)",
     "legendFormat": "{{involvedObject_kind}}"
    }
   ]
  },
  {
   "title": "By Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$job\"}| __error__=\"\"[$__interval])) by (type)",
     "legendFormat": "{{involvedObject_kind}}"
    }
   ]
  },
  {
   "title": "By Cluster",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$job\"}| __error__=\"\"[$__interval])) by (cluster_name)",
     "legendFormat": "{{involvedObject_kind}}"
    }
   ]
  },
  {
   "title": "TOP 10  Kubernetes Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10,sum by (reason) (count_over_time({job=\"$job\"} | __error__=\"\"[$__interval])))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "TOP 10  Kubernetes Namespaces in Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(10,sum by (namespace) (count_over_time({job=\"$job\"} | __error__=\"\"[$__interval])))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Kubernetes Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{job=\"$job\", namespace=~\"$namespace\", kind=~\"$kind\", reason=~\"$reason\", type=~\"$type\"}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Kubernetes Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{stream=~\".+\", kubernetes_namespace_name=~\"$namespace\"} |= ``"
    }
   ]
  }
 ]
}