{
 "title": "Ingester",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{ namespace=~\"$namespace\", container=\"loki\", pod=~\"loki-write.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{ namespace=~\"$namespace\", container=\"loki\", pod=~\"loki-write.*\"} / container_spec_cpu_period{ namespace=~\"$namespace\", container=\"loki\", pod=~\"loki-write.*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{ namespace=~\"$namespace\", container=\"loki\", pod=~\"loki-write.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{ namespace=~\"$namespace\", container=\"loki\", pod=~\"loki-write.*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{ job=~\"($namespace)/loki-write\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}