apiVersion: v2
name: aws-load-balancer-controller
description: AWS Load Balancer Controller Helm chart for Kubernetes

version: 2.5.2

dependencies:
  - name: aws-load-balancer-controller
    version: 2.5.2
    repository: https://aws.github.io/eks-charts
