aws-load-balancer-controller:
  # causes TLS usses
  enableServiceMutatorWebhook: false
  # keepTLSSecret specifies whether to reuse existing TLS secret for chart upgrade
  keepTLSSecret: true
  enableCertManager: true
  resources:
    requests:
      cpu: 10m
      memory: 72Mi
    limits:
      memory: 72Mi
  rbac:
    create: true
  serviceAccount:
    create: true
  serviceMonitor:
    enabled: true
