aws-load-balancer-controller:
  clusterName: dev-wgt7
  serviceAccountName: aws-load-balancer-controller
  serviceAccount:
    create: true
    automountServiceAccountToken: false
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::106102538874:role/aws-lb-controller"
