aws-load-balancer-controller:
  createIngressClassResource: false
  # keepTLSSecret specifies whether to reuse existing TLS secret for chart upgrade
  keepTLSSecret: true
  resources:
    limits:
      memory: 72Mi
    requests:
      cpu: 10m
      memory: 72Mi
  rbac:
    create: true
  serviceAccount:
    create: true
