apiVersion: v1
kind: LimitRange
metadata:
  name: apps-limits
  namespace: apps
spec:
  limits:
    # defaults set to 1.5 ratio
  - default: # this section defines default limits
      cpu: null
      memory: 24Mi
    defaultRequest: # this section defines default requests
      cpu: 10m
      memory: 16Mi
    max: # max and min define the limit range
      cpu: "1"
      memory: 1000Mi
    min:
      cpu: 10m
      memory: 10Mi
    # this basically means overcommitment ratio
    maxLimitRequestRatio:
      cpu: {{ .Values.limits.apps.cpu }}
      memory: {{ .Values.limits.apps.memory }}
    type: Container
