# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: apps-limits
#   namespace: apps
# spec:
#   limits:
#   - default: # this section defines default limits
#       cpu: 25m
#       memory: 24Mi
#     defaultRequest: # this section defines default requests
#       cpu: 20m
#       memory: 16Mi
#     max: # max and min define the limit range
#       cpu: "1"
#       memory: 1000Mi
#     min:
#       cpu: 10m
#       memory: 10Mi
#     maxLimitRequestRatio:
#       cpu: "1.5"
#       memory: "1.5"
#     type: Container
