apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/aeternity/gitops-apps.git
      revision: {{ .Values.defaultTargetRevision }}
      directories:
      - path: aepp-base
      - path: app
        exclude: true
      - path: app-secrets
        exclude: true
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: apps
      source:
        repoURL: https://github.com/aeternity/gitops-apps.git
        targetRevision: {{ .Values.defaultTargetRevision }}
        path: '{{.path.path}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{ .Values.defaultTargetRevision }}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
