{{- if and (.Capabilities.APIVersions.Has "external-secrets.io/v1beta1") .Values.external.values -}}
{{- $prefix := .Values.external.remotePrefix }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "argocd.fullname" . }}-repo-creds
  labels:
  {{- include "argocd.labels" . | nindent 4 }}
    argocd.argoproj.io/secret-type: repo-creds
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: awssm
    kind: ClusterSecretStore
  target:
    {{- if .Values.external.secretName }}
    name: {{ .Values.external.secretName }}
    {{- else }}
    name: {{ include "argocd.fullname" . }}-repo-creds
    {{- end }}
    creationPolicy: Owner
  data:
  {{- range $key, $value := .Values.external.values }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $prefix }}{{ $value }}
  {{- end }}
{{- end -}}
