---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "argocd.fullname" . }}-secret-test
  labels:
    app.kubernetes.io/name: {{ include "argocd.fullname" . }}-secret-test
    app.kubernetes.io/part-of: {{ include "argocd.fullname" . }}
    {{- include "argocd.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.encValues }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "argocd.fullname" . }}-secret-test
        app.kubernetes.io/part-of: {{ include "argocd.fullname" . }}
        {{- include "argocd.labels" . | nindent 8 }}
