{
 "title": "Aeternity / Instances",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "sd_node_exporter" }
  ]
 },
 "panels": [
  {
   "title": "Number of Instances per Envrionment",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (env) (up{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Instances by Environment",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (env) (up{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances by Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (region) (up{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance_type) (up{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "AWS Instances",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}