{
 "title": "Aeternity / Blockchain",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(aecore_chain_height,env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (env) (aecore_chain_height)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (env) (aecore_chain_total_difficulty)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX Pool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (env) (aecore_txpool_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verified Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (env) (aecore_peers_bucket{bucket=\"verified\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max by (env) (aecore_chain_height)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (env) (aecore_chain_total_difficulty)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max by (instance) (aecore_sync_progress)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Transaction Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Transaction Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg by (env, status) (aecore_txpool_push_total)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "avg by (env) (aecore_txpool_size)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "avg by (env, bucket) (aecore_txpool_gc_total)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Buckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg by (env, bucket) (aecore_peers_bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "avg by (env, direction) (aecore_peers_connection)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Pings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "avg by (env, status) (aecore_peers_ping)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Mining", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Attempts per 3min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "avg by (env) (rate(aecore_mining_retries_total[$__rate_interval]) * 60)",
     "legendFormat": "retries"
    },
    {
     "expr": "avg by (env) (rate(aecore_mining_blocks_total[$__rate_interval]) * 60)",
     "legendFormat": "blocks"
    }
   ]
  }
 ]
}