{
 "title": "Aeternity / Job Queues",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "sd_statsd_exporter" },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(up{job=\"$job\"},env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$job\", env=\"$env\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Accepted Queue Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (exported_name) (rate(aecore_queues_size{job=\"$job\", instance=\"$instance\", status=\"accepted\"}[$__rate_interval]))",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Rejected Queue Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (exported_name) (rate(aecore_queues_size{job=\"$job\", instance=\"$instance\", status=\"rejected\"}[$__rate_interval]))",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Accepted Jobs Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (exported_name) (aecore_queues_wait{job=\"$job\", instance=\"$instance\", status=\"accepted\"})",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Rejected Jobs Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (exported_name) (aecore_queues_wait{job=\"$job\", instance=\"$instance\", status=\"rejected\"})",
     "legendFormat": "{{exported_name}}"
    }
   ]
  }
 ]
}