{
 "title": "Aeternity / Node Exporter / USE Method / Group",
 "description": "The USE Method / Cluster Dashboard for the Prometheus Node Exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": "sd_node_exporter" },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(up{job=\"$job\"},region)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(up{job=\"$job\"},env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  instance:node_cpu_utilisation:rate1m{job=\"$job\", region=~\"$region\", env=~\"$env\"}\n*\n  instance:node_num_cpu:sum{job=\"$job\", region=~\"$region\", env=~\"$env\"}\n)\n/ scalar(sum(instance:node_num_cpu:sum{job=\"$job\", region=~\"$region\", env=~\"$env\"}))\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "CPU Saturation (load1 per CPU)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_load1_per_cpu:ratio{job=\"$job\", region=~\"$region\", env=~\"$env\"}\n/ scalar(count(instance:node_load1_per_cpu:ratio{job=\"$job\", region=~\"$region\", env=~\"$env\"}))\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"$job\", region=~\"$region\", env=~\"$env\"}\n/ scalar(count(instance:node_memory_utilisation:ratio{job=\"$job\", region=~\"$region\", env=~\"$env\"}))\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Memory Saturation (Major Page Faults)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "instance:node_vmstat_pgmajfault:rate1m{job=\"$job\", region=~\"$region\", env=~\"$env\"}",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Net Utilisation (Bytes Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate1m{job=\"$job\", region=~\"$region\", env=~\"$env\"}",
     "legendFormat": "{{instance}} Receive",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate1m{job=\"$job\", region=~\"$region\", env=~\"$env\"}",
     "legendFormat": "{{instance}} Transmit",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Net Saturation (Drops Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "instance:node_network_receive_drop_excluding_lo:rate1m{job=\"$job\", region=~\"$region\", env=~\"$env\"}",
     "legendFormat": "{{instance}} Receive",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "instance:node_network_transmit_drop_excluding_lo:rate1m{job=\"$job\", region=~\"$region\", env=~\"$env\"}",
     "legendFormat": "{{instance}} Transmit",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk IO Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_seconds:rate1m{job=\"$job\", region=~\"$region\", env=~\"$env\"}\n/ scalar(count(instance_device:node_disk_io_time_seconds:rate1m{job=\"$job\", region=~\"$region\", env=~\"$env\"}))\n",
     "legendFormat": "{{instance}} {{device}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_weighted_seconds:rate1m{job=\"$job\", region=~\"$region\", env=~\"$env\"}\n/ scalar(count(instance_device:node_disk_io_time_weighted_seconds:rate1m{job=\"$job\", region=~\"$region\", env=~\"$env\"}))\n",
     "legendFormat": "{{instance}} {{device}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Space Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without (device) (\n  max without (fstype, mountpoint) (\n    node_filesystem_size_bytes{job=\"$job\", region=~\"$region\", env=~\"$env\", fstype!=\"\"} - node_filesystem_avail_bytes{job=\"$job\", region=~\"$region\", env=~\"$env\", fstype!=\"\"}\n  )\n) \n/ scalar(sum(max without (fstype, mountpoint) (node_filesystem_size_bytes{job=\"$job\", region=~\"$region\", env=~\"$env\", fstype!=\"\"})))\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  }
 ]
}