{
 "title": "Aeternity / Protocol",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "sd_statsd_exporter" },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(up{job=\"$job\"},env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_chain_current_difficulty{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max by (env) (aecore_chain_height{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    { "expression": "$A / ($B/1000)", "type": "math" }
   ]
  },
  { "title": "Generations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Key Block Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_keyblock_interval_ms{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Key Block Propagation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_keyblock_propagation_ms{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Number of Micro Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_generation_microblocks{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Number of Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_generation_transactions{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Micro Forks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (rate(aecore_aemon_microforks_total{job=\"$job\", env=~\"$env\"}[$__rate_interval]))",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Micro Forks Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_microforks_height{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  { "title": "Micro Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Micro Block Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_microblock_interval_ms{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Micro Block Propagation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_microblock_propagation_ms{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Number of Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_microblock_transactions{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Gas Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_microblock_gas{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Transaction Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_transaction_size_bytes{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Transaction Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_transaction_gas{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Confirmation Delay (Blocks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_confirmation_delay{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true
  },
  {
   "title": "Contracts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Monitoring Transactions in a Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_generation_mon_transactions{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_publisher_queue_size{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Expired Transactions (TTL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_publisher_queue_expired{job=\"$job\", env=~\"$env\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "[$env] Post Transactions /1min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "repeat": "env",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(aecore_aemon_publisher_transactions_total{job=\"$job\", env=\"$env\", status=\"success\"}[$__rate_interval]) * 60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "[$env] Post Transactions by Error /1min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "repeat": "env",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(aecore_aemon_publisher_transactions_total{job=\"$job\", env=\"$env\", status!=\"success\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}