{
 "title": "Aeternity / Erlang",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "sd_statsd_exporter" },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(up{job=\"$job\"},env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$job\", env=\"$env\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "erlang_system_processes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "processes"
    }
   ]
  },
  {
   "title": "System IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(erlang_system_io{job=\"$job\", instance=\"$instance\", type=\"in\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "rate(erlang_system_io{job=\"$job\", instance=\"$instance\", type=\"out\"}[$__rate_interval]) * -1",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "erlang_system_memory_system_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "erlang_system_memory_allocated_bytes{job=\"$job\", instance=\"$instance\", type=\"processes\"}",
     "legendFormat": "processes"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "erlang_system_memory_allocated_bytes{job=\"$job\", instance=\"$instance\", type!=\"processes\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "System Monitor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "erlang_system_monitor_busy_dist_port{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "busy dist port"
    },
    {
     "expr": "erlang_system_monitor_busy_port{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "dist port"
    },
    {
     "expr": "erlang_system_monitor_large_heap{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "large heap"
    },
    {
     "expr": "erlang_system_monitor_long_gc{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "long gc"
    },
    {
     "expr": "erlang_system_monitor_long_schedule{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "long schedule"
    }
   ]
  }
 ]
}