{
 "title": "Aeternity / Protocol",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Difficulty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_chain_current_difficulty)",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Height",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "max by (env) (aecore_chain_height)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Generations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Key Block Interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_keyblock_interval_ms)",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Key Block Propagation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_keyblock_propagation_ms)",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Number of Micro Blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_generation_microblocks)",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Number of Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_generation_transactions)",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Micro Forks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_microforks_total)",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Micro Forks Height",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_microforks_height)",
       "legendFormat": "{{env}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Micro Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Micro Block Interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_microblock_interval_ms)",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Micro Block Propagation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_microblock_propagation_ms)",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Number of Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_microblock_transactions)",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Gas Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (env) (aecore_aemon_microblock_gas)",
       "legendFormat": "{{env}}"
      }
     ]
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Transaction Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_transaction_size_bytes)",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Transaction Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_transaction_gas)",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Confirmation Delay (Blocks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_confirmation_delay)",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "Contracts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Monitoring Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_generation_mon_transactions)",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Transactions by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env, status) (aecore_aemon_publisher_transactions_total)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_publisher_queue_size)",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Expired Transactions (TTL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (env) (aecore_aemon_publisher_queue_expired)",
     "legendFormat": "{{env}}"
    }
   ]
  }
 ]
}