apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller

version: 10.25.0

dependencies:
  - name: traefik
    version: 10.25.0
    repository: https://helm.traefik.io/traefik
