apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller

version: 22.3.0

dependencies:
  - name: traefik
    version: 22.3.0
    repository: https://helm.traefik.io/traefik
