apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller

version: 10.24.1

dependencies:
  - name: traefik
    version: 10.24.1
    repository: https://helm.traefik.io/traefik
