apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller

version: 10.1.1

dependencies:
  - name: traefik
    version: 10.1.1
    repository: https://traefik.github.io/traefik-helm-chart
