apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller

version: 17.0.5

dependencies:
  - name: traefik
    version: 17.0.5
    repository: https://helm.traefik.io/traefik
