apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller

# > 22.0.0 for k8s 1.22+ support
# < 28.0.0 because of containo.us CRD API
# 27.X because of Treafik v2

# kubectl apply --server-side --force-conflicts -k 'github.com/traefik/traefik-helm-chart/traefik/crds?ref=v23.0.0'
version: 27.0.2

dependencies:
  - name: traefik
    version: 27.0.2
    repository: https://helm.traefik.io/traefik
