defaultCertificateDmains: []
traefik:
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi

  topologySpreadConstraints:
  # This forces the scheduler to put traefik pods on nodes where no other traefik pods are scheduled.
   - labelSelector:
       matchLabels:
         app.kubernetes.io/name: traefik
     maxSkew: 1
     topologyKey: kubernetes.io/hostname
     whenUnsatisfiable: ScheduleAnyway
   - labelSelector:
       matchLabels:
         app.kubernetes.io/name: traefik
     maxSkew: 1
     topologyKey: topology.kubernetes.io/zone
     whenUnsatisfiable: ScheduleAnyway

  deployment:
    replicas: 3

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 15
    metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 60

  globalArguments: []
  additionalArguments:
    - "--entrypoints.web.http.redirections.entrypoint.to=:443"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    - "--metrics.prometheus.addServicesLabels=true"
  logs:
    access:
      enabled: true
  ingressClass:
    enabled: true
    isDefaultClass: true
  service:
    single: false
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
  ports:
    websecure:
      tls:
        enabled: true
    https:
      port: 10443
      expose: true
      exposedPort: 8443
      protocol: TCP
      tls:
        enabled: true
    metrics:
      expose: true
  tlsStore:
    default:
      defaultCertificate:
        secretName: traefik-default-cert
  metrics:
    prometheus:
      serviceMonitor:
        enabled: true
        honorLabels: true
