traefik:
  globalArguments: []
  additionalArguments:
    - "--entrypoints.web.http.redirections.entrypoint.to=:443"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  logs:
    access:
      enabled: true
  service:
    spec:
      # externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: stg-g2ml-traefik-ingress
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:106102538874:certificate/604a0c23-94a0-4c63-ae50-869ed1e39c9f,arn:aws:acm:eu-central-1:106102538874:certificate/0672ef01-e688-45e4-8880-a107d3c7aab7"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
