apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: dincho@aeternity.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: le-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: traefik
          ingressTemplate:
            metadata:
              annotations:
                # traefik.ingress.kubernetes.io/router.tls: "true"
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
    - dns01:
        route53:
          region: us-east-1
          role: {{ .Values.dnsSolverRole }}
      selector:
        dnsZones:
          {{- toYaml .Values.dnsSolverDomains | nindent 10 }}
        matchLabels:
          "solver": "route53"
