loki:
  global:
    deploymentMode: SingleBinary
  loki:
    singleBinary:
      replicas: 0
    storage:
      type: s3
    test:
      enabled: false
    lokiCanary:
      enabled: false
    gateway:
      enabled: false
    ingress:
      enabled: false
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: s3
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
