apiVersion: v2
name: external-secrets
description: External secret management for Kubernetes

version: 0.9.0

dependencies:
  - name: external-secrets
    version: 0.9.0
    appVersion: "v0.9.0"
    repository: https://charts.external-secrets.io
