apiVersion: v2
name: external-secrets
description: External secret management for Kubernetes

version: 0.10.2

dependencies:
  - name: external-secrets
    version: 0.10.2
    appVersion: "v0.10.2"
    repository: https://charts.external-secrets.io
