external-secrets:
  priorityClassName: system-cluster-critical
  resources:
    limits:
      memory: 42Mi
    requests:
      cpu: 10m
      memory: 42Mi

  webhook:
    create: true
    resources:
      limits:
        memory: 32Mi
      requests:
        cpu: 10m
        memory: 32Mi

  certController:
    resources:
      limits:
        memory: 90Mi
      requests:
        cpu: 10m
        memory: 90Mi
