external-secrets:
  priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 20m
      memory: 42Mi
    limits:
      cpu: 25m
      memory: 42Mi

  webhook:
    create: true
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        cpu: 25m
        memory: 32Mi

  certController:
    resources:
      requests:
        cpu: 20m
        memory: 192Mi
      limits:
        cpu: 25m
        memory: 128Mi
