rabbitmq:
  global:
    imageRegistry: ""
    imagePullSecrets: []
    storageClass: ""
  image:
    registry: docker.io
    repository: bitnami/rabbitmq
    tag: 3.12.4-debian-11-r0
    debug: true
    pullPolicy: IfNotPresent
    pullSecrets: []
  auth:
    ## @param auth.username RabbitMQ application username
    ## ref: https://github.com/bitnami/containers/tree/main/bitnami/rabbitmq#environment-variables
    ##
    username: user
    ## @param auth.password RabbitMQ application password
    ## ref: https://github.com/bitnami/containers/tree/main/bitnami/rabbitmq#environment-variables
    ##
    password: secretpassword
    #password: rabbitmq-secret/rabbitmq-password
    #password: {{ .Values.encValues.rabbitmq-password | b64enc | quote }}
    ## @param auth.securePassword Whether to set the RabbitMQ password securely. This is incompatible with loading external RabbitMQ definitions and 'true' when not setting the auth.password parameter.
    ## ref: https://github.com/bitnami/containers/tree/main/bitnami/rabbitmq#environment-variables
    ##
    securePassword: true
    ## @param auth.existingPasswordSecret Existing secret with RabbitMQ credentials (must contain a value for `rabbitmq-password` key)
    ## e.g:
    ## existingPasswordSecret: name-of-existing-secret
    ##
    existingPasswordSecret: ""
    ## @param auth.enableLoopbackUser If enabled, the user `auth.username` can only connect from localhost
    ##
    enableLoopbackUser: false
    ## @param auth.erlangCookie Erlang cookie to determine whether different nodes are allowed to communicate with each other
    ## ref: https://github.com/bitnami/containers/tree/main/bitnami/rabbitmq#environment-variables
    ##
    erlangCookie: ""
    ## @param auth.existingErlangSecret Existing secret with RabbitMQ Erlang cookie (must contain a value for `rabbitmq-erlang-cookie` key)
    ## e.g:
    ## existingErlangSecret: name-of-existing-secret
    ##
    existingErlangSecret: ""
  persistence:
    ## @param persistence.enabled Enable RabbitMQ data persistence using PVC
    ##
    enabled: true
    ## @param persistence.storageClass PVC Storage Class for RabbitMQ data volume
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""
    ## @param persistence.selector Selector to match an existing Persistent Volume
    ## selector:
    ##   matchLabels:
    ##     app: my-app
    ##
    selector: {}
    ## @param persistence.accessModes PVC Access Modes for RabbitMQ data volume
    ##
    accessModes:
      - ReadWriteOnce
    ## @param persistence.existingClaim Provide an existing PersistentVolumeClaims
    ## The value is evaluated as a template
    ## So, for example, the name can depend on .Release or .Chart
    ##
    existingClaim: ""
    ## @param persistence.mountPath The path the volume will be mounted at
    ## Note: useful when using custom RabbitMQ images
    ##
    mountPath: /bitnami/rabbitmq/mnesia
    ## @param persistence.subPath The subdirectory of the volume to mount to
    ## Useful in dev environments and one PV for multiple services
    ##
    subPath: ""
    ## @param persistence.size PVC Storage Request for RabbitMQ data volume
    ## If you change this value, you might have to adjust `rabbitmq.diskFreeLimit` as well
    ##
    size: 50Gi
    ## @param persistence.annotations Persistence annotations. Evaluated as a template
    ## Example:
    ## annotations:
    ##   example.io/disk-volume-type: SSD
    ##
    annotations: {}
    ## @param persistence.labels Persistence labels. Evaluated as a template
    ## Example:
    ## labels:
    ##   app: my-app
    labels: {}
  ingress:
    enabled: true
    path: /
    pathType: ImplementationSpecific
    hostname: "rabbitmq.dev.aepps.com"
    annotations:
      kubernetes.io/ingress.class: traefik
  ## Network Policy configuration
  ## ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
  ##
  networkPolicy:
    ## @param networkPolicy.enabled Enable creation of NetworkPolicy resources
    ##
    enabled: false
    ## @param networkPolicy.allowExternal Don't require client label for connections
    ## The Policy model to apply. When set to false, only pods with the correct
    ## client label will have network access to the ports RabbitMQ is listening
    ## on. When true, RabbitMQ will accept connections from any source
    ## (with the correct destination port).
    ##
    allowExternal: true
    ## @param networkPolicy.additionalRules Additional NetworkPolicy Ingress "from" rules to set. Note that all rules are OR-ed.
    ## e.g:
    ## additionalRules:
    ##  - matchLabels:
    ##    - role: frontend
    ##  - matchExpressions:
    ##    - key: role
    ##      operator: In
    ##      values:
    ##        - frontend
    ##
    additionalRules: []
