apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: default-http-backend
 annotations:
  traefik.ingress.kubernetes.io/router.priority: "1"

spec:
  defaultBackend:
    service:
      name: traefik
      port:
        number: 80
