{{- if and (.Capabilities.APIVersions.Has "cert-manager.io/v1") .Values.defaultCertificateDmains -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-default-cert
  labels:
    solver: route53
spec:
  secretName: traefik-default-cert
  dnsNames:
    {{- toYaml .Values.defaultCertificateDmains | nindent 4 }}
  issuerRef:
    name: letsencrypt
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
{{- end -}}
