signoz:
  #default values while we found all configs
  zookeeper:
      autopurge:
          purgeInterval: 1
  
  kafka:
      zookeeper:
          enabled: false
      externalZookeeper:
          servers: ["signoz-zookeeper:2181"]
      zookeeperConnectionTimeoutMs: 6000
  
  druid:
      image:
        tag: 0.21.1-rc2
  
      configVars:
          # To store data on local disks attached
          druid_extensions_loadList: '["druid-histogram", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage", "druid-kafka-indexing-service"]'
          druid_storage_type: local
  
  
          # # To store data in S3
          # druid_extensions_loadList: '["druid-histogram", "druid-datasketches", "druid-lookups-cached-global", "postgresql-metadata-storage", "druid-kafka-indexing-service", "druid-s3-extensions"]'
          # druid_storage_type: s3
          # druid_storage_bucket: signoz-druid
          # druid_storage_baseKey: baseKey
          # AWS_ACCESS_KEY_ID: <your secret id>
          # AWS_SECRET_ACCESS_KEY: <your secret key>
          # AWS_REGION: <your region>
  
      historical:
          persistence:
              size: "20Gi"
  
      zkHosts: "signoz-zookeeper:2181"
  
      zookeeper:
          enabled: false
  
  flattener-processor:
      configVars:
        KAFKA_BROKER: signoz-kafka:9092
        KAFKA_INPUT_TOPIC: otlp_spans
        KAFKA_OUTPUT_TOPIC: flattened_spans
  
  query-service:
      configVars:
        DruidClientUrl: http://signoz-druid-router:8888
        DruidDatasource: flattened_spans
  
  frontend:
    config:
      name: signoz-nginx-config
      queryServiceUrl: signoz-query-service:8080
    ingress:
        # -- Enable ingress for Frontend
        enabled: true
        # -- Ingress Class Name to be used to identify ingress controllers
        className: ""
        # -- Annotations to Frontend Ingress
        annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        # cert-manager.io/cluster-issuer: letsencrypt-prod
        # -- Frontend Ingress Host names with their path details
        hosts:
        - host: signoz.stg.aeternity.io
            paths:
            - path: /
                pathType: ImplementationSpecific
                port: 3301
        # -- Frontend Ingress TLS
        tls: []