encValues:
  dex.github.clientSecret: "AgBLiQhoTPPxUr0LxA7UznE0iZQZwiwvYNVZLKIjpZ0RjZZN/gd3sUjTzgXJPga3Fwch/k/3ClZ5jUm5vWTbs7b8i7CivIEMbpBqOahjdC5wgxliIcZ3eBfcl138rEq1G7R5e67RejcG2sW7Bi9Y54VAzucoClppX22zBPOc1TjHlCWGY4JBzZubgzRNMd70vXICAMdiQQc8gaB0dWOdCU3X11SK8NadPqSn+zcqikHsc++Ta9LykygYF/YdCq+CwzKCfhmF2aLROoKfIJ/4lTlQ8Z9bcsiHpP52tgt9E/HxDuZj4/cDLd3kN3h9g+LgPI8ZijC5cOvjq+N/7N8APTPEUyR2rFRCNqaVwM7tqYFc/aGJZqglhPpWOxV0C1AEocFxZLhvzOEF7FuGIewBd+BIkUlnSJqF/qOmj6hA56LPbTG/9VFf7e43hH5ViIBX/pMpRafPcA/YYNYq6hVloS87vFRJKzb2JHwyd5byOAPW6/bo30TiNK02laVrXxhrAWHbjCEYymPw1TAAsY9jxw4j8keYxMP/4wuVU8LfS+xZAe1uDYtuPfjxjY0J3SU4UC9kX6QP6VIh9dIcil6jKG76Gtus15vhmaIcr8dLQsJbV71goZ8U5NMQHENye3BlUMBpdsL/QzUrE03pgoxn3vOeRMWQyAeYh2rqcPsuwo/taGPaPy2PZS0YR5MMBICPdzK1UPxtEQ=="
  admin.password: "AgAcBrDTe7u4/4Z1VcqoQETWS4u1XcpedwlaX/xuOC7yrdqZMGk9e+qnMNHlSwjS484f0ZisHpgOKMV1yrNxBWDWnZm4xy8ZORIdwR+OsdguDTyJJSPo7JrE+dbFnqUMrbcx8cPT1q/7CMcs/XI14q6xBaC8cDIR78tLyGJRtL7HV+PzbgpvMlc195Lje4R+nPU8RmoaVK9/iMUIWqxkxdnrC2Qqtq3sIvmUg7EgkkkYmruI13iMuqaW8K7aO6CE/utXtkId6Um9gcR5lnoIAS6XcBdZ2M7nONhz1y5XiGK/r+or0WW51OvwDjdNZPEJlR69N+TJ94oGW9O6dna43HaD+ash4JLoYwsOHk2JLdKKWqbAsbknpKlt9iv87/+9KYvMa0d4nhr793DraDxpiKMNm54oJO1u8ptuvTT4UN0jgEuStfJwtiYUac1b2o2zgQkjvUm7u3X+zYyZgZFxVflQIcSYtzyxoB9JoePGWrAiCC8xr6wTbCvrURvns3IrrAoZ1+h5Iq0libnFqXnsd2ONgmXPWxmVdsPbPBoymro3B9g7MqSz+Xpj0DWA1xxiWjml79/itp7Z+PPjKh8a+2jhcuHjXp6KV99NsC4CNOqkyw84REOrjmRCadWFL+gxGkI8LuW5sSR1F9DLX67r+eviSYaZV4y9cc71uJwOz/UfrVEaAJyVMNaQRnTuD7bZsHa09kKChGA7noszpQ=="
  admin.passwordMtime: "AgBeRc2b1iW0+x1bVy4Trm8mR5V/fgbDTYZEf/V3947Sc3fr3S49wPrzEQLAElq47bQUkoKaehmqvx0k8epGBR3ZKuB/zAdTaTZ4ZxzGdBKtDHBcXZwWGssjhUXJpNwaMhVix6WxAHQOHRo1cKWf42s0XZtm08PGhpv26DkTZQgG7s2PpahGo4hyZ34dSOVHu5UQYbm31x/MCuVia6Ts/7KqGspr7+RWWiysI1c15VC5X0pzUlTNg99p+Nh5bgMhFWIzDmMjOp6aYcJEjmdgYxgaPD7h/kNiKIQuM/xc4yU+ela4WOq0iKcjxWUW4uquIYxoNp/FUgF0Lf97qLtTa9tiKeUpN3zDCXkx50HUIseg5ZiSYDDb5JKLuY2cGRjTtyd7TCPpsRc6NPhfHjiX23BnB6NjzzZ6GQwjlmwTkfFSbEqApMIIJpuGecxEdDi3GDaRa8DSEvoTIA+jSdvQ7734Os17pea6R0dQPZQ/hvdoJ6FMfiElU0SFWL3xxN5IUO9WbDg2r3yFxcF/Lr/jCw6+hPkMadhv09z7rf9IPNdg3OmxClpPVlADcg/8/W0wrA9lmAl5nKwHd1kssMVLmbVRrkdvMCrNk4VCd4ggBGN8/qobgSJJIJRAlgb3MbuCI7lRj7JVZaXCEBumXbCJNk4sPvkfEoExU23hnUGM2keXAAVDGAWOQrTCcKoPtZhgOugByUPDNODdPQ9fS9RORef0dJx/LG9td8M="

defaultRepoUrl: 'https://github.com/aeternity/gitops-tools.git'
defaultTargetRevision: dev

applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
  aws-load-balancer-controller:
    project: tools
    namespace: kube-system
  traefik:
    project: tools
    namespace: traefik

argo-cd:
  configs:
    secret:
      createSecret: false
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      pathType: ImplementationSpecific
      hosts:
        - "argocd.dev.aeternity.io"
    extraArgs:
      - --insecure=true
    logLevel: debug
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.dev.aeternity.io/
      # Argo CD instance label key
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - url: https://github.com/aeternity/gitops-tools.git
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
        - type: helm
          url: https://helm.traefik.io/traefik
          name: traefik
        - type: helm
          url: https://prometheus-community.github.io/helm-charts
          name: prometheus-community
        - type: helm
          url: https://aws.github.io/eks-charts
          name: eks
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: aabbccddeeff00112233
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: aeternity
      # oidc.config: |
      #   requestedIDTokenClaims:
      #     groups:
      #       essential: true
      #   requestedScopes:
      #     - openid
      #     - profile
      #     - email
    additionalProjects:
      - name: tools
        namespace: argocd
        additionalLabels: {}
        additionalAnnotations: {}
        description: Tools used to run the environment
        sourceRepos:
          - 'https://github.com/aeternity/gitops-tools.git'
        destinations:
          - namespace: tools
            server: https://kubernetes.default.svc
          - namespace: argocd
            server: https://kubernetes.default.svc
          - namespace: sealed-secrets
            server: https://kubernetes.default.svc
          - namespace: kube-system
            server: https://kubernetes.default.svc
          - namespace: traefik
            server: https://kubernetes.default.svc
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
