defaultTargetRevision: prd

app-secrets:
  external:
    remotePrefix: /k8s/prd-0e9c

argo-cd:
  server:
    ingress:
      hosts:
        - "argocd.prd.aeternity.io"
      tls:
        - hosts:
          - "argocd.prd.aeternity.io"
          secretName: argocd-cert
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.prd.aeternity.io

applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
  external-secrets:
    project: tools
    namespace: external-secrets
  aws-load-balancer-controller:
    project: tools
    namespace: kube-system  
  traefik:
    project: tools
    namespace: traefik
  metrics-server:
    project: tools
    namespace: kube-system
  kube-prometheus-stack:
    project: tools
    namespace: monitoring
  kube-prometheus-blackbox-exporter:
    project: tools
    namespace: monitoring
  fluent-bit:
    project: tools
    namespace: logging
  cluster-autoscaler:
    project: tools
    namespace: cluster-autoscaler
  kubernetes-event-exporter:
    project: tools
    namespace: kubernetes-event-exporter
  velero:
    project: tools
    namespace: velero
  cert-manager:
    project: tools
    namespace: cert-manager
  superhero-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  superhero-wallet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  aepp-base:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  aerepl-http:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  aesophia-http:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  mdw-frontend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  superhero-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  dex-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  dex-backend-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  dex-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  aepp-faucet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  graffiti-server:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  aepp-graffiti:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  explorer:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  ga-multisig-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  state-channel-demo-frontend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  state-channel-demo-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
    
namespaces:
  - tools
  - apps
  - aenodes
