defaultTargetRevision: stg

app-secrets:
  external:
    remotePrefix: /k8s/stg-m4n4

argo-cd:
  global:
    domain: argocd.stg.aeternity.io
  configs:
    cm:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.stg.aeternity.io

