defaultTargetRevision: dev

external:
  secretName: argocd-github-token
  remotePrefix: /k8s/dev-wgt7
  values:
    "password": /argocd/GITHUB_TOKEN
    "url": /argocd/GITOPS_AELABS_URL
    "username": /argocd/GITOPS_AELABS_USER

app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7

argo-cd:
  configs:
    cm:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.dev.aeternity.io
  server:
    ingress:
      hosts:
        - "argocd.dev.aeternity.io"

additionalApplications:
  - name: nginx
    project: tools
    namespace: tools
  - name: dev-net-aenode
    project: aenodes
    namespace: aenodes
    repoUrl: 'https://github.com/aeternity/gitops-nodes.git'
    targetRevision: master
  - name: dev-net-snapshoot
    project: aenodes
    namespace: aenodes
    repoUrl: 'https://github.com/aeternity/gitops-nodes.git'
    targetRevision: master
  - name: aepp-hc-ui
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  - name: aepp-base-hc
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  - name: aws-ebs-csi-driver
    project: tools
    namespace: kube-system
  - name: external-snapshotter
    project: tools
    namespace: kube-system
  - name: test-repo
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: hedgedoc
    project: tools
    namespace: hedgedoc
  - name: postgresql
    project: tools
    namespace: wikijs
  - name: wikijs
    project: tools
    namespace: wikijs
  - name: hedgedoc-2
    project: tools
    namespace: hedgedoc-2
  - name: postgresql-hedgedoc
    project: tools
    namespace: hedgedoc-2
  - name: aescan
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: aescan-testnet
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
