encValues:
  dex.github.clientID: "AgCkNccgqgoECGmeBedKgAZCEaHq2A1IWZaratmwJu3qjuwBjMPjRJjIXcpvVNlFiSFQPx5mbSwiD2bBfLpI++Yw+oSj5sJtjnXGFj58jA/vo0Z5KNYu4CX5apFpk6z4g70+BRUYszqeVLn78xvALqS/D8qH/nAjsXw7AKY/SqXgEJNdh4a/xssLxqrWNSrkxu0QfevOOAfiwNpUY8uiav6QJDbCS3wPmfBwIZyT67TBwDa0olzThbf6AwxRNhn3gY/6jGO2k2d6VhUn+fnvy9n8jjvCl9rdLnACdHgd/UPEtXvH/LsK7S2ODLNJqTpvx8sk/CwPf9zMK9CIW/Vss9+NC8gmOydcX3I6/BCS3kVSAgN77oTb1XgkNunLfthbZVsR4YUvve9nnOXmrSUXYw5zPyUiWU2lBMZNRvL+7JoQ8nUmvDWBIzD8PF2P4gTBNGbKX0hrs4gY+KY8ZOmHCYYzeaprBRy/RJMf/4ZLgxsOzM2xhFW5Bg8mU2YXL182NvCoyab58OoZVW85tfe3WNHH2mi3g+/oi84d+rlnta0GAR6lfcw/3wM8h/nhnPKFL4Be2ibPJW9UlejDskuXdS7lJupxoQwZRHwpJi5AsDEZaLRRMjQF4BIZIki8wsOBThfCCT4W+CLlUunsgS726Js8aJ9C03QNrRaY4pAYiEp1vxrNB94/Xpo620IaQ4aDGdNc9BUJZtqp+mV2OLqAW/5nGgM+dQ=="
  dex.github.clientSecret: "AgBJKr4v8Zg0f3AoivLe4YgLoLOncFcrFWK5pJhGtByO+Gt0MAYN/aDi58NsHoj/YOaiUMEpt0I+GARMH2VBAmMoJFvYcHoM8+VXT0nAPJ6S7Fdun4LVrBFrM2e1IAHzdF2j3+r9/MkoJbQpXFJLIPtvxZSXcWJUiB+iid0Bbw4NnzGTJ3jjx24smhEfz75mQHhkBEVrMZaq7WOd7nPHhC/oazoTfbweFdsNfb1nsLNJ6HkptwcTV9L8hLKh8jvEFJzdwxdjUWUDqaDyZyxr+1h5fxK5fL/ZHbQCsHyq4hF/U7fbr0sbf3SOFxpDwB0PbWuFLbL82xTfF6Y5b2V9rbxXa1a4Pqrk+ATNWriGCWmPG1JVZzwdqHcze3Ru2+zt5B0bNFCG+NcYBDKZUJ8vrFUXRm2TPtWoaG2JXD6ZEDPvOHa7bsmfX/BSaasPd3Lh3qta+l+3M5UFfShn1d+oo6unikStxBLorSaHOw2B64zlemtnTHEXDf+sP8UoN246tsLRC9+ycxShLdlh3NYGLSKVgM6llFH/Jl6bBlW6cr2dIm3j7MHbI8c4DpLFx0JDyQ4/ygvRfTaUQkT3VhKQFeqgBb3QY3PWGRX/mlSHPT6iVOThUKqNOLkBp934X8Vi3YkbK+6K7NUOR76qH4toviNw2+IFl9D7i6K64z2DZ+05tDcyWE2NKUwvBuQ4McSCIqFEve4aJKVaWrj5SpizdNVz0eaQZF3/X4ejL7UwFUcuZVAOlZdBKd+P"
  server.secretkey: "AgAsRw0ElnUtVAEF5OpM2f72K0xBkMFVadn7n6bUzKieh5C8FfNZWGwMhCr9ODSpVKZFx4qiLPvv9vT+3jJjKre8jc87tp0aMxeynTINjKaSz2QtRw7UOt7Y4Kp7c3ppQxLZ7o1f4DhFqmcqSy3q/sI/IpHItaPsMfWGO85Mzu0odRAre9UooDzHc302LSuiftwzB4OfTv2R2JFduGd/KXZgGVujqjFnGOly/ip0kNjeLcIkw2hGQ3j1V73Qewu/HVfKbywzRxQrsUEH3Yv80HubCn+neU5opWnSSc9D/v7e23sxSvaiMJLS6T1uFoG/Pfo8Lhy/IQcY7k1X662aOPOjmghWqCjjXTbhZViUhw+03LoXc24n0iNnB8sGv1kKhXgWL0xa1ga4JPkPPFhLJWppkg2wK4XRuumGAUI6SIQZ4QGku49uIBaSZ2oJwy5E8wpa6aovbb4gJXmcVKob69QM3oygUGIijhBKo2yRgduPGif/RAoIIVWKhcH1tLWnNcBB1ZvOp82111Kphufr+b7JOiGGDvleb7+cM/A+9UcKrEzEDJ0vakvaGpYhGeyMyumexN3y2BVRC+oQH0pkfeiTg5PGffcsSokHpuP+nhZERzPP/Ow/vN6+o9d30LO44fgn77uurgvGNQeyZ5WtZF88DDxv7S37OSiOiKOZVjNjCFh54y0sOWVfhA0pQsAWe1vZShdR4w/ApnwjnYqBnmyGTwYsWM0mV6Y="
  admin.password: "AgBtJpzaXZ120K8jUjvrbP5xq7qifSd8bH0GrTdoCLxo8u+2NqBClezZWQST2qx2MmJdpqjknAev+5QpwT9CgBl3A7lCWWNpLo/t4MuWd/pTiibP85WJcIy4DVFUJT9Bb/0y1g+5JemDps/iJwqJBPs72qfso3L8FV8lSiTu+w5ynKN8IB+5htsJp7irQPC41YCET5XnUa0aT8Uu7t4pY3zywW6JzdBuirwDg935KORzDbJTU/1igBFpegzBTK9epGQsO3hc5AfxQq2s96oCDv7aOeh5zisElvhHU587bgSPyGpKFtgPXXkS3DCDACo7mUxGpB6ucjFg9Xq9T2Nc4/UssAj4HvEhQgvFWsav4MPvgsExRzKclaXM0cXczDQuhf1XfeELhOJhs9bE1V+6tfJdx8vS+I63k50Z7pHj4GG9S51n2sgwp7DXomqnPFg/ROnTKFKW6ZeQJDhg0T60Afs8sRC3MsLhVxkuJRBziKz9Zm9IRIc4qyJkr6eEHjf8w433Zi/JgdX8qpLxhrmleXmHL9NM5mdztzq/41VukqUXyZSXBa4xL1q5ooX9ai1PYa4lcf23JfnOgMIcv/p1e+pdQ6kceZAq2ZuVAqKqB6shHo0IpaCIa7WDB9PT+ytw+utv2Ufi9qBPoIBm67RtW1f5J1+7uT+NaHeBrnqWCg5YH8e8wnYl8wKl7YLifOhYpsLGkRtcVzBHTKYUBZTr"
  admin.passwordMtime: "AgBXOGnvRyAG+N54/vdbe11Jjx1/YkzxBHY1RXSZ4v63KLpPPN6iCi7YlqLqetKeVW2T0HpSJR6WQFzL4QNL0/kT0CF7H6lcXneyhseas4GOwX1CDHTdsQZeK7rpckmfyfQobJrVewpGvE5PFQjaZeKRcNwI+jkqlw/GFK5ZaZWSisydNU14AD6PDvWIVWMo5aYv6232DaRxYxbQHOIVT/7hmiAd4kGtIBtvhAiKdnWPXJW6bx4y2Rg4GwdKybu6s0kCmjrn/kd5MoZVUyk7s5BD8BFnov39vwq8v+WnKE4jP4wCAEB4fGoGYroXrTxRGJ5cG+0CXspzw4CAmgfPAgveuJjbbCbRKAw2pQKmkPJBEILozH63WNddnQRkiROkSOt0eT7boB6d25pykympkRGeY5OYf0LT89/TSr14vfQt7uoXG87Yo6qkNA50fdliszie3lzxZuZ8QgMHlLzL4TaW4GeEltR0V17TMYTPWoL/mQjhBl+lp0wQYM2aoD2R92Ar+qLk7XUVRqZYzCrKFZBJNUfZpus4DbG+Le3hGdrSWCZewwy2j/XiCQPONUWTFkWFetcA5FUQlPADXwqfJoWjX5jv1ukrVMuhVGEnLoUbQi1I9UjQ1pWUx0pISdfP3rt3B7zqAknMnYMe7/DjGUCpX7bp3bR+wJpej02QKFl1NuKKCshzeKw4jco57NcFb2ldTgL6Jm4XCezFCp2ng4qcnzWWwR7O"
argo-cd:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      pathType: ImplementationSpecific
      hosts:
        - "argocd.stg.aeternity.io"
    extraArgs:
      - --insecure
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      # url: https://argocd.example.com
      # Argo CD instance label key
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - url: https://github.com/aeternity/gitops-tools.git
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
        - type: helm
          url: https://aws.github.io/eks-charts
          name: eks
        - type: helm
          url: https://helm.traefik.io/traefik
          name: traefik
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: aeternity
    additionalProjects:
      - name: tools
        namespace: argocd
        additionalLabels: {}
        additionalAnnotations: {}
        description: Tools used to run the environment
        sourceRepos:
          - 'https://github.com/aeternity/gitops-tools.git'
        destinations:
          - namespace: tools
            server: https://kubernetes.default.svc
          - namespace: argocd
            server: https://kubernetes.default.svc
          - namespace: sealed-secrets
            server: https://kubernetes.default.svc
          - namespace: kube-system
            server: https://kubernetes.default.svc
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'

defaultRepoUrl: 'https://github.com/aeternity/gitops-tools.git'
defaultTargetRevision: staging

applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
  aws-load-balancer-controller:
    project: tools
    namespace: kube-system
  traefik:
    project: tools
    namespace: traefik
