defaultTargetRevision: dev

app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7

argo-cd:
  configs:
    cm:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.dev.aeternity.io
  server:
    ingress:
      hosts:
        - "argocd.dev.aeternity.io"

additionalApplicationsets:
  - name: apps-dev
    repoUrl: https://github.com/aeternity/gitops-apps.git
    # targetRevision: master #see defaultTargetRevision
    include:
      - aepp-test
      - aepp-hyperchain
      - aepp-base-hc
    project: apps
    appNamespace: apps
    syncPolicy:
      # Set Application finalizer
      preserveResourcesOnDeletion: true

additionalApplications:
  - name: external-snapshotter
    project: tools
    namespace: kube-system
