defaultTargetRevision: dev

external:
  secretName: argocd-github-token
  remotePrefix: /k8s/dev-wgt7
  values:
    "password": /argocd/GITHUB_TOKEN
    "url": /argocd/GITOPS_AELABS_URL
    "username": /argocd/GITOPS_AELABS_USER

app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7

argo-cd:
  configs:
    cm:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.dev.aeternity.io
  server:
    ingress:
      hosts:
        - "argocd.dev.aeternity.io"

additionalApplications:
  - name: nginx
    project: tools
    namespace: tools
  - name: dev-net-aenode
    project: aenodes
    namespace: aenodes
    repoUrl: 'https://github.com/aeternity/gitops-nodes.git'
    targetRevision: master
  - name: aepp-hc-ui
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  - name: aepp-base-hc
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  - name: external-snapshotter
    project: tools
    namespace: kube-system
