encValues:
  dex.github.clientID: "AgCpy6qwXaKTYKWu1fZWKjdi/gvn/+Q+J2n+0ofZe/z56RENsqL6P/ceU7/mkw9A19dAcu2uoyvaVm72JhEBNCNLRdUuxJahPsmWFAqxs7AwPq6evRSuy+7FUk7qf4j/ZtbW+F33KA1LvsIq+dhbBy9qbHsMBh54fqhz0w7ggJhpdGmNEd0/DDh9hThZBvzbEBTIOy7crl43gy3WVqj+9EwGTtsIu0l6C8P0ptIG9cVoSsIXB/VAY4e4su60BYHlWug4ECbbV3hI6utaV13ror+isRvAIC8Eu5xfq+lABA1L7l8r0YjBIpd4ubQmjDgKfg2me81XN+vJYjBWUKSnEGSnw0NISuDRnkytBXVu6xAnrMYn0iEfNzG1BgWFdhe0FIgeNe8OnNOAzlExKCHpwPUUz860Rr9EcilT4L/HU9Q9yEqzpYYwoVjNHFlbOhOW3X2sHRaPKL1nc34qM7zRSu5dsm4KOKPM/3KAcQ50AbKwwuOwrrTFVgSC01TRWEyaJNFRomNNyvHIV6Law8KpA0hOQtUzcYfJb710rGSylkqHar7GzMwPkmEDXDQmwuoJoABxu7O9XGbB0I9YL0Ud3k+o/pU8XbC/4ePqY8nX7Sh3BecITXiCMzcdt5JMhYNk0nZoWTYYBI3Zq74xK0tcj0YjzA6W+Zlldeq6E2vo/h6OXH6NBrimDZz63FgUllYcm5hPIh/wadGJRMY1U+3qaR+/jU4Xpw=="
  dex.github.clientSecret: "AgC/pQaF2/7RXABTGU/VixZ3nrJpLPQtQ+YCDfzV1YMQC+YQ0NffmGAtfpv1cu5g4GXHucMGdQP5ll8LEO3MOsuvdYSI99ZFcWsJoobTwhvHM2ZMsIFDv21Uan6pvxfaHfkdZ2xZAk5NqK5RG8OvCv9C1YWm49CP33foxyKJkh27PXPugYyBcdkSMtBYM49C1c6UCxB0r98DHy/IY6tf8XP1hf37Cv51y0qtf9xxI/DilTkA/pMFyNdXfx0SJ9J878vprJGfsrKDVCugpwCqb5YuI3xwprGGslBLGFEW6aYB/eVT58prGe2fQtXf3eZaEWd+TptyaJnYFk8yLz5pIGKR2Va4QdNb0ayivZuwfR+uxql8TQ/c6oPeR3z8omUuKXnu6Xsva4FVyJLbw3IiBN5TAfCSiBQsnJgFYbQ8WvH1wVs9EkbjTOpTRXerhXmo9Ro9dDOFwVbaPnlhgWqOFDO9V5ot9Anu8xLVsl5zDOTOn1VLxfDgT5RSNe9fJzlC5j1Uyrc8zbk4XXKz47DLDikjFLPzb8xJsvxNllSby0/UjUDRDzNX+zro4TViDWmY25xrHDAhd4xpcyIDMTNkpGh3NzOJP7y+GKFX8YcWJAHJZKU1FFh66d1VoaGdVuviTsLnCZk5yCICbeYLMDO2/JhdpcYLz+4UHg52fdTJuCwvTcnRupZsr+kvKSOB5n73Xr+1koGsFoXTfmuTpZ2h8oeT9PpyeZin7vK9noUhh/shKts7dxnvrZ3C"
  server.secretkey: "AgBVhlACpbZRwYkOWraHOl8MO4tpoRrJqkRvRPOdT84x7okTOKedxiX3I7ylJ7qSEEahZllTSMEzd61e//hJ264IOd+6X8DMy8jedw5q9P9zPjZAG/IRuIObzpQhOev7EdZnpsjW5bhpwSGGi8h98LlLNF4d1Aj6YRQ5fAYBdmvpIIB433G27f3aT+IF5gUX+YCAXjVIg2fFuZqRssp2mrVHqg5MF+beLph1eselwl11QTGkg9XemJcaIW9phXL+XW4DqnaDpR/iJvTBhLAihFDCP8jZ5+OhutCYbf3wEhAZAvUwXiyjbLtIVp1RwsRGSrvFjxO0azwuGP//h1+1Mj2nALaAaKEYInnVi4M9x2KZV7frrhwSTgqCLZVZ4j6+8MrGlE2ms+gZrMxCLJxqgeUdXy82iAeRQyMieD3iprR7HwBgI+azKMYkjHC6shaD1z/NrX0iM6Bw1+O9IOKumDCT2yY3MpUhtSE137sxDW8VIyvaxVCLH5BsQlquXRHXv3oi1euia0tRdIXsoazsqJs2b6ZdQuKALTIvUZCL7WqypLjnAfNyXtD1fOXwvS6AB6Cbl7xZvB+fjTEMTCHialOPpZYykZSvrhn/+PED/PgQFCrgb8AO7xbojdCouc9TJX0xrLf9mtXxLrduBPqshAVf2CaB1bfGkpHzefe7jaqMhL54vlQHeOgn0evm/eumXhqiJkaZ57D9Nwp5HMaq/VoFUEEsrdTy4Q0="

argo-cd:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      pathType: ImplementationSpecific
      hosts:
        - "argocd.stg.aeternity.io"
    extraArgs:
      - --insecure
      - --repo-server-timeout-seconds=180
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      # url: https://argocd.example.com
      # Argo CD instance label key
      url: https://argocd.stg.aeternity.io
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - url: https://github.com/aeternity/gitops-tools.git
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
        - type: helm
          url: https://aws.github.io/eks-charts
          name: eks
        - type: helm
          url: https://helm.traefik.io/traefik
          name: traefik
        - type: helm
          url: https://charts.bitnami.com/bitnami
          name: bitnami
        - type: helm
          url: https://fluent.github.io/helm-charts
          name: fluent
        - type: helm
          url: https://kubernetes.github.io/autoscaler
          name: cluster-autoscaler
        - type: helm
          url: https://vmware-tanzu.github.io/helm-charts
          name: velero
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: aeternity
      resource.customizations: |
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/failurePolicy
        admissionregistration.k8s.io/ValidatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/failurePolicy
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, aeternity:devops, role:admin
    additionalProjects:
      - name: tools
        namespace: argocd
        additionalLabels: {}
        additionalAnnotations: {}
        description: Tools used to run the environment
        sourceRepos:
          - 'https://github.com/aeternity/gitops-tools.git'
        destinations:
          - namespace: tools
            server: https://kubernetes.default.svc
          - namespace: argocd
            server: https://kubernetes.default.svc
          - namespace: sealed-secrets
            server: https://kubernetes.default.svc
          - namespace: kube-system
            server: https://kubernetes.default.svc
          - namespace: traefik
            server: https://kubernetes.default.svc
          - namespace: monitoring
            server: https://kubernetes.default.svc
          - namespace: logging
            server: https://kubernetes.default.svc
          - namespace: cluster-autoscaler
            server: https://kubernetes.default.svc
          - namespace: kubernetes-event-exporter
            server: https://kubernetes.default.svc
          - namespace: velero
            server: https://kubernetes.default.svc
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
      - name: apps
        namespace: argocd
        additionalLabels: {}
        additionalAnnotations: {}
        description: Applications deployed on EKS
        sourceRepos:
          - 'https://github.com/aeternity/gitops-apps.git'
        destinations:
          - namespace: apps
            server: https://kubernetes.default.svc
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
defaultRepoUrl: 'https://github.com/aeternity/gitops-tools.git'
defaultTargetRevision: stg

applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
  aws-load-balancer-controller:
    project: tools
    namespace: kube-system
  traefik:
    project: tools
    namespace: traefik
  metrics-server:
    project: tools
    namespace: kube-system
  kube-prometheus-stack:
    project: tools
    namespace: monitoring
  kube-prometheus-blackbox-exporter:
    project: tools
    namespace: monitoring
  fluent-bit:
    project: tools
    namespace: logging
  cluster-autoscaler:
    project: tools
    namespace: cluster-autoscaler
  kubernetes-event-exporter:
    project: tools
    namespace: kubernetes-event-exporter
  velero:
    project: tools
    namespace: velero
  superhero-ui-web:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  superhero-ui-ssr:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  superhero-wallet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  aepp-base:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  aerepl-http:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  aesophia-http:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  mdw-frontend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  superhero-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  dex-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  dex-backend-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  dex-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  aepp-faucet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  test-repo-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  test-repo-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  graffiti-server:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  aepp-graffiti:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  state-channel-demo-frontend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  state-channel-demo-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  explorer-frontend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'

namespaces:
  - tools
  - apps
