defaultTargetRevision: stg

external:
  secretName: argocd-github-token
  remotePrefix: /k8s/stg-m4n4
  values:
    "password": /argocd/GITHUB_TOKEN
    "url": /argocd/GITOPS_AELABS_URL
    "username": /argocd/GITOPS_AELABS_USER

app-secrets:
  external:
    remotePrefix: /k8s/stg-m4n4
    values:
      "password": /argocd/GITHUB_TOKEN
      "url": /argocd/GITOPS_AELABS_URL
      "username": /argocd/GITOPS_AELABS_USER

argo-cd:
  configs:
    cm:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.stg.aeternity.io
  server:
    ingress:
      hosts:
        - "argocd.stg.aeternity.io"

additionalApplicationsets:
  - name: apps-stg
    repoUrl: https://github.com/aeternity/gitops-apps.git
    # targetRevision: master #see defaultTargetRevision
    include:
      - aepp-test
    project: apps
    appNamespace: apps
    syncPolicy:
      # Set Application finalizer
      preserveResourcesOnDeletion: true
