defaultTargetRevision: dev

app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7

argo-cd:
  server:
    ingress:
      hosts:
        - "argocd.dev.aeternity.io"
      tls:
        - hosts:
          - "argocd.dev.aeternity.io"
          secretName: argocd-cert
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.dev.aeternity.io

additionalApplications:
  - name: dev-net-aenode
    project: aenodes
    namespace: aenodes
    repoUrl: 'https://github.com/aeternity/gitops-nodes.git'
    targetRevision: master
  - name: dev-net-snapshoot
    project: aenodes
    namespace: aenodes
    repoUrl: 'https://github.com/aeternity/gitops-nodes.git'
    targetRevision: master
  - name: aepp-hc-ui
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  - name: aepp-base-hc
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  - name: aws-ebs-csi-driver
    project: tools
    namespace: kube-system
  - name: external-snapshotter
    project: tools
    namespace: kube-system
  - name: redis
    project: tools
    namespace: redis
  - name: governance-server
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
