encValues:
  dex.github.clientID: "AgCC76QDmeIYoVQGIt5tvcnSOKd/EEDebWUwrSW0QM2VIVEuw/GXixA3cIxIfbdbV2azDEwRhYYXsVJXJJ9L57wLXcCGxxLBGHKXlQzbeEcEgQfD4LkleULL+E8/whApnO8JAZzHNkiL+DYjY1PlOlQub3Yl0HZaRJwCQIq0SazUQ1+W261bv/R0rdpTNLjwxhplo0rofC/AkQu1ymCAkWCIJaJbrWMr8NtGb7+mg7geNB8U2ogtYsE3TIE1nNGXFLEIvpmm75HeESZFXDKDDeB25EtuVLy4fbCFUsLK/JbGOYtjyVsp0xioe0fgz6lAJuJUHYUZtnt531c7BWCJQCZHt+oq7kTzoaclJm5b6glGUYp1mJ1rRHKhiPZoH9I3HZJG7/f+qiJwCSTtUSe9rj9YxATzACE61WcWPy/2TDIvc+Yo4gb5DXVViNWcr872u2766WiFb7D+LVIFnLimMvk8vSd93IbcSBDOWyhFtxwOxOIjvQhXcdJB9GeVefiPGQyCH+NqUqIq1ZdTdlRTGQGWN34zg5Ydupubfm9gaEWeWkXp3DfslSph8/OwIXuWDGpmMBam9njJUK9gsDCfCh1tXl+0+g0uqKRG72cwySZR1lrlHejGPoRgZgWzhp4bY6kS3oZUk5Q4BLvemmzwvv8qWIQmSe36SjSlcz+zO9nN40PomyY8Bt44KWOfw/3eV/sciFYF/z/ZLza1Y8p5Wu6Y8nXSSA=="
  dex.github.clientSecret: "AgBavE7ArKSmSyOQEPGLeRmcwByqqrCRDf7DEQD2nKN79+Q44oXsVTNjELxzBbJEc4Ty3stpnYPiEXqTOhUwgySe4yaf3js6Fk8TvoMZQ3nc6dp5d2NZ/ZICuTnJxhnGktXex61BA3RF9N8yTfy4ANGJnNpClV3uMC/O4stOFOuXkOOgwvLbU6I21/jph/CMOdksWKM0ohcX0vKyKLgMPhXEuMAO0WeVBe0bQ2KC4niQMWWf79vgthVin8zUvERMuJCD5KTqKMTztJHM17phLG3gc7cgqp5C6QEcFld4rOadEuLXlZNkzsHLQcWXLxMN4fz+ZFOGCxH5rqy+0J49AnP+mtuLW+0zEfcwtjnPmrlsNVkJHibzMRLx5inQZ+ivKhPlk56DX2ezVULRzxZ6CF+OfirgQUie5HU/9g1pQuXsJU/pFiE3h2e36q7+Y/co/waEWmHCfP45DA+Po2kMvH3NlKgHZ0MBfeXKfxaHeC6/ItDLUnTA4z/yk4fvIhok4giL8tpcC2IWZQdwCCc2vtoj2ShD/4C79N2EEp6Ffo/c58U5SRnXcyhJUXU3h42Ygb7MGN9D9qjA65aVQ/0SYvXJJnI+k8IUMF2yS1bCUKeQ5/oabhZdJrkd2LnqFM7Abysq9RIGMpj8OelDkI/MgciwOpie3hKphcVnRo5H4ild8l4aWyRREjqIcvFI0jwMcRMIasyPHjTRFRU/fhFgDK47waI6m0y5Sm+CjpJkX5oFll9dBdGXP6ud"
  admin.password: "AgCU25nlo8UMRHjW2yFLdwjJm2GYYwj1YRi0UcV9QU1JD4tUme589Q98/AQ8KGJEEpNXE66sI8XAOqNTBr9PkoxozGZN/TFBTn5o4+bfHLihOvDo10RtvvQYV9QJ4HfAJw2Eduk+ETj8OGOm52HAwKOvOk+/l7fL8tkuiN32TRtsOpKtT5vToHAEd80troOSCvl/tnDtuE48knn1JfuO1OEkxRdjMfBU3152BfROfOQj1uox5KFwMb54OGicU5QupOu2QoZgv5fVXggvNHnneT3kjQlIyyD2u5oq10spxorTpJh/aJZPE8oqCDWmpz3eAKBidf4cJEmDAH3KJH73Hk0szEJumAKXeA3lpZoTDz/8/B+AFSUyh9WRptMoC/8BQf8aRiPi/jMkILnFBxIc0GYcheGTFiwvP0og4BpKpDS/mZTUBov9Qu5oiN/iwZrQGCMeyhiAIE+gUR6Dx3HtKS52FQ3jv96N+OHDQTEJ+RBr7VJm323Mi46NPuvJUXpiAY6X1sOpW+ISAFdngZdyRND/9axa8ixPCIEhgaxAx4URiN1bLFwNK6s4dxO0ezyFyDX0ccIKFD+EJjANkcTMGW1S22WS9LLin4rVyXTr4M+5iwX1ziK1XQKe0yx7nsJIEginNKGLngUgnxi3CD15jKLVj3qAB6tkaFvHNEOQ4twcSghttx5uUvK498+9AjPjja0fE6YJdvrtVNOax6Xcvg=="
  admin.passwordMtime: "AgBUAYFCZukFY92o8MmGyBZaiycwbl0OlkhOtRT6x1xZ28nTN78j6mOkTleARJlhdsyMsskOSryCdHjQqiQcRFrJEG3eY7jBkcVY6Uf/bwyESdOoNIrEyJZeRgagRG/fqDJxCA4BzJ9PFPs/JpnLgwzA/a5OuEJxDoKUsP+6RmWFkmuYNlo/CYKEjdXhsaSIodmw8DGjt5q9/6txfNcSfamjtJZ9xwtZvKnD9mP1Zni/gyhetylGr7NGRYOpn5uQkjJ6sGzOJn7FYlzXGlZOjq2fjpWTKb6bEAhW24ddNXQAe+X1a3RTKsGjvFBxQ5heRfVSJHPpf7sd0RMp8iaY95kqk53qmk6BJwRuhKJtCjG01XF9buEqX8aOI3LRgSBBDGT7disQJTjgB9R0Q76mshzNnJiWLskqNA8QEb3+pbe2lHm0a/GdGwo7wxPP791fNo6bvatMVf1jBkbOIABowNbum7h1I+HhyLnFYRxhNQWDRwAfgT+cB2damyv7kZEU/Zh50KPT7j8oXRlYkgVeA9ts6q2DsO08sTzykgq4sVI2+EKD8HCEwFoHE82G2FSODADxeyZMHA1p/nCkjaKYAcxaH5hO0Ic+iWkPPOL1ObJN45FX21v8tpkXokM7sTcZQ7tH1gEw2cja04KvKRYDW1uIdr0N5nO2eH+RBBxXJTcbEI1hilH6eBIl9FCeVJ6o8W5Ey93iCbTBp3ldZIDubX6y84z/xSe8"
  server.secretkey: "AgCV0bOSj5M/2/sV7N1qPwT9wjjuc3pnsfAhWSpjPhbCCEA5L0z5RAkiDc7Of1t5Vsj7E2TSnea2W+BXQSo56fa6XqOmJPOVwl6VqdxiGF3S/B7GdurBwvDIkVR5UGQcngtUt/1mn7TKskr3Bx6XUNDHT6TiqD0khaSjNOOfuiK2DGjqSBNu6JflkNzH/UxMHCppoSCTtvxKRXYNPhcWXiz21yjdubXcrZPriEajjzFGTSdxOPdjlN7f5hhrm8Nd/eXf7yOn/DEnjYdd24rpHQJRZCltpzHhhcf+yYJSNcfsTyK+M3/P7pjz888uGkNaXzHwNU6Ehy65kNWhFMzms9Wta7F/RzR8ziNDNPuOLikjgDEkNhwfqFysPuMpBE9ylA1UCyiDNWpFFxq4JkhT7+uyE3YaE5q887/qXyX6NJLf+HTYFPC++k9RtPw2gNOccQclFOmLGSRuumLFVs86qHkWiUYVLXb7VM7k2gu4QoN6zTcOZZHmRgxMQJ/THXUauFPmGoqcLHN12mv70/5EXPmGdpgjgJJDQ9rdSZ81ZiOLRdT7p1RcVQ9V7GL/6nk0LtW9fKbILbfoeFt5NL+SQYjAX9SrEBaL8+k4dRGaYKfQr+pNgjU+Lnsndwfgj5uUDxmzovS3MQ+wRkR+CQ0TYJqTaCp9Y02QVFcWBWQ+ZSppDt50FoQLSt3co3TGcbulqFUfeH2ZrcV5S6Jl4p9VWsqO/3sccVpNSIg="
defaultRepoUrl: 'https://github.com/aeternity/gitops-tools.git'
defaultTargetRevision: staging

namespaces:
  - tools
applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
argo-cd:
  configs:
    secret:
      createSecret: false
  server:
    extraArgs:
      - --insecure
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      # Argo CD instance label key
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - url: https://github.com/aeternity/gitops-tools.git
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: aeternity
    additionalProjects:
      - name: tools
        namespace: argocd
        additionalLabels: {}
        additionalAnnotations: {}
        description: Tools used to run the environment
        sourceRepos:
          - 'https://github.com/aeternity/gitops-tools.git'
        destinations:
          - namespace: default
            server: https://kubernetes.default.svc
          - namespace: tools
            server: https://kubernetes.default.svc
          - namespace: argocd
            server: https://kubernetes.default.svc
          - namespace: sealed-secrets
            server: https://kubernetes.default.svc
           # server: staging-cluster how to deploy 
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
