argo-cd:
  server:
    extraArgs:
      - --insecure
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      # url: https://argocd.example.com
      # Argo CD instance label key
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        # - url: git@github.com:group/repo.git
        #   sshPrivateKeySecret:
        #     name: secret-name
        #     key: sshPrivateKey
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
      # oidc.config: |
      #   name: AzureAD
      #   issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
      #   clientID: CLIENT_ID
      #   clientSecret: $oidc.azuread.clientSecret
      #   requestedIDTokenClaims:
      #     groups:
      #       essential: true
      #   requestedScopes:
      #     - openid
      #     - profile
      #     - email
