defaultTargetRevision: dev

app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7

argo-cd:
  server:
    ingress:
      hosts:
        - "argocd.dev.aeternity.io"
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.dev.aeternity.io
