encValues:
  dex.github.clientID: "AgCC76QDmeIYoVQGIt5tvcnSOKd/EEDebWUwrSW0QM2VIVEuw/GXixA3cIxIfbdbV2azDEwRhYYXsVJXJJ9L57wLXcCGxxLBGHKXlQzbeEcEgQfD4LkleULL+E8/whApnO8JAZzHNkiL+DYjY1PlOlQub3Yl0HZaRJwCQIq0SazUQ1+W261bv/R0rdpTNLjwxhplo0rofC/AkQu1ymCAkWCIJaJbrWMr8NtGb7+mg7geNB8U2ogtYsE3TIE1nNGXFLEIvpmm75HeESZFXDKDDeB25EtuVLy4fbCFUsLK/JbGOYtjyVsp0xioe0fgz6lAJuJUHYUZtnt531c7BWCJQCZHt+oq7kTzoaclJm5b6glGUYp1mJ1rRHKhiPZoH9I3HZJG7/f+qiJwCSTtUSe9rj9YxATzACE61WcWPy/2TDIvc+Yo4gb5DXVViNWcr872u2766WiFb7D+LVIFnLimMvk8vSd93IbcSBDOWyhFtxwOxOIjvQhXcdJB9GeVefiPGQyCH+NqUqIq1ZdTdlRTGQGWN34zg5Ydupubfm9gaEWeWkXp3DfslSph8/OwIXuWDGpmMBam9njJUK9gsDCfCh1tXl+0+g0uqKRG72cwySZR1lrlHejGPoRgZgWzhp4bY6kS3oZUk5Q4BLvemmzwvv8qWIQmSe36SjSlcz+zO9nN40PomyY8Bt44KWOfw/3eV/sciFYF/z/ZLza1Y8p5Wu6Y8nXSSA=="
  dex.github.clientSecret: "AgBavE7ArKSmSyOQEPGLeRmcwByqqrCRDf7DEQD2nKN79+Q44oXsVTNjELxzBbJEc4Ty3stpnYPiEXqTOhUwgySe4yaf3js6Fk8TvoMZQ3nc6dp5d2NZ/ZICuTnJxhnGktXex61BA3RF9N8yTfy4ANGJnNpClV3uMC/O4stOFOuXkOOgwvLbU6I21/jph/CMOdksWKM0ohcX0vKyKLgMPhXEuMAO0WeVBe0bQ2KC4niQMWWf79vgthVin8zUvERMuJCD5KTqKMTztJHM17phLG3gc7cgqp5C6QEcFld4rOadEuLXlZNkzsHLQcWXLxMN4fz+ZFOGCxH5rqy+0J49AnP+mtuLW+0zEfcwtjnPmrlsNVkJHibzMRLx5inQZ+ivKhPlk56DX2ezVULRzxZ6CF+OfirgQUie5HU/9g1pQuXsJU/pFiE3h2e36q7+Y/co/waEWmHCfP45DA+Po2kMvH3NlKgHZ0MBfeXKfxaHeC6/ItDLUnTA4z/yk4fvIhok4giL8tpcC2IWZQdwCCc2vtoj2ShD/4C79N2EEp6Ffo/c58U5SRnXcyhJUXU3h42Ygb7MGN9D9qjA65aVQ/0SYvXJJnI+k8IUMF2yS1bCUKeQ5/oabhZdJrkd2LnqFM7Abysq9RIGMpj8OelDkI/MgciwOpie3hKphcVnRo5H4ild8l4aWyRREjqIcvFI0jwMcRMIasyPHjTRFRU/fhFgDK47waI6m0y5Sm+CjpJkX5oFll9dBdGXP6ud"
defaultRepoUrl: 'https://github.com/aeternity/gitops-tools.git'
defaultTargetRevision: staging

namespaces:
  - tools
applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
argo-cd:
  server:
    extraArgs:
      - --insecure
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      # Argo CD instance label key
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - url: https://github.com/aeternity/gitops-tools.git
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: aeternity
    additionalProjects:
      - name: tools
        namespace: argocd
        additionalLabels: {}
        additionalAnnotations: {}
        description: Tools used to run the environment
        sourceRepos:
          - 'https://github.com/aeternity/gitops-tools.git'
        destinations:
          - namespace: default
            server: https://kubernetes.default.svc
          - namespace: tools
            server: https://kubernetes.default.svc
          - namespace: argocd
            server: https://kubernetes.default.svc
          - namespace: sealed-secrets
            server: https://kubernetes.default.svc
           # server: staging-cluster how to deploy 
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
