defaultTargetRevision: stg

external:
  secretName: argocd-github-token
  remotePrefix: /k8s/stg-m4n4
  values:
    "password": /argocd/GITHUB_TOKEN
    "url": /argocd/GITOPS_AELABS_URL
    "username": /argocd/GITOPS_AELABS_USER

app-secrets:
  external:
    remotePrefix: /k8s/stg-m4n4
    values:
      "password": /argocd/GITHUB_TOKEN
      "url": /argocd/GITOPS_AELABS_URL
      "username": /argocd/GITOPS_AELABS_USER

argo-cd:
  configs:
    cm:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.stg.aeternity.io
  server:
    ingress:
      hosts:
        - "argocd.stg.aeternity.io"
      tls:
        - hosts:
          - "argocd.stg.aeternity.io"
          secretName: argocd-cert

additionalApplications:
  - name: test-repo
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: aescan
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
