defaultTargetRevision: dev

app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7

# overcommitment ratio
limits:
  apps:
    cpu: "3.0"
    memory: "1.5"

argo-cd:
  configs:
    cm:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.dev.aeternity.io
  server:
    ingress:
      hosts:
        - "argocd.dev.aeternity.io"
  applicationSet:
    resources:
      requests:
        cpu: 25m
  controller:
    resources:
      requests:
        cpu: 300m
  repoServer:
    resources:
      requests:
        cpu: 250m

additionalApplicationsets:
  - name: apps-dev
    repoUrl: https://github.com/aeternity/gitops-apps.git
    # targetRevision: master #see defaultTargetRevision
    include:
      - aepp-test
    project: apps
    appNamespace: apps
    syncPolicy:
      # Set Application finalizer
      preserveResourcesOnDeletion: true

additionalApplications:
  - name: external-snapshotter
    project: tools
    namespace: kube-system
