defaultTargetRevision: dev

external:
  secretName: aelabs-repo-creds
  remotePrefix: /k8s/dev-wgt7
  values:
    "password": /argocd/GITHUB_TOKEN
    "url": /argocd/GITOPS_AELABS_URL
    "username": /argocd/GITOPS_AELABS_USER

app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7

argo-cd:
  configs:
    cm:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.dev.aeternity.io
  server:
    ingress:
      hosts:
        - "argocd.dev.aeternity.io"

additionalApplications:
  - name: nginx
    project: tools
    namespace: tools
  - name: aepp-hc-ui
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  - name: aepp-base-hc
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps.git'
  - name: external-snapshotter
    project: tools
    namespace: kube-system

  - name: aescan
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: aescan-testnet
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: superhero-ui
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: superhero-wallet
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: superhero-backend
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: dex-ui
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: dex-backend-mainnet
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: dex-backend-testnet
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: aepp-graffiti
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: graffiti-frontend
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: graffiti-server-mainnet
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: graffiti-server-testnet
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: state-channel-demo-frontend
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: state-channel-demo-backend
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: ga-multisig-backend-mainnet
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: ga-multisig-backend-testnet
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  - name: ga-multisig-ui
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
