encValues:
  dex.github.clientSecret: "AgAy1KBDvsHSe1ah9mx+CmYbBxaX6jFdCuF3G7hp9LDEEUBA75KUjZvv9knLSuxx4ZvtkuM6wkSQ9lWxWkso990N4T2yznEuSyHc9Tq1uNiZug8QxhzS2aAOQxdT6ASAoylBVKKwEgLSOq02HMqZeTXUDOpAkC1zR5aIu4JpDwZuxr1URET+WZPLxd+W2tqeoWbCSe9Cu7iL15vXiJPDEWu8qmmnxXjR+Ozx8xdELXgzszfbDbZtIQHlntG4kKnx9l6KQ6bbuQbpEUHBBulmY0yrcQeCXOnC7RquRDiTuhtFFKcqm2gmzWQ04YFse1UmHaCVMCiSRwoMeaRmRUo2RbOb2O1jFTh9ZvfZp7Wj4ky/8oAATnqPnAogZKDNZHK+8msxSfdIB2693BF8ZG0Q9b8L+SNu5En1UNUjuU03fza8Zzs3WT2se5WGA7kXdTj6YF1YKn6j/5Lq1+sg6iASOfLJhVnxojRGM49Xm9jmbUf81WoR0JJZqdg8UYu0fyePJ01Y56jF8IBDFiATypCIthMMexfBtVcFope4HIy6AMGaNTlO16VJDtobWK4ssKMGQi86m6EFqVOz3tuwoZxj4JIvGvb9u6+lw3VHWLC9Ld7jOv5pqpIe/sXTMQgvb9gIGZDMpYRWpdHO6blDAulOyaHal9ZT9r2OBtsCLsaJlLMzq9s0zgROZXB5at3Lb6lQCDxKNpF7uw=="
  admin.password: "AgBC4u9ZEmBvxsI4ZUR4jR9JIEDl2sdKKVKjq1cfALRAzOYn4hv0cgPU6oU0KRD2phjB1KqjrDXWft0fWib175veuDQLg5Hf4Y1R+q/gvejlW7y3pKaN76JJIxILQKdfqZ3aJ/faqMXb05jW+54XSudPUcjPOPjErj+pzguADZ5RNQv3gFIjeqZX8LmDqwsLZI3yjURpbYfmC19LPXuzpplGqac+VLMHGIV/g3Ru1zhq2GDQHehmyA4mrmZ2Aj+QSIMVPo2qWbTm9pSm6Xfp2UpKzjxdcOkfnbNJhQxCRxSmfoTW37/YhVGfec8tEZ2ecLKsxoap6kUr25z75lSS0O60/LGAO4yx0zQOftvZEjV57zKGa7NgiWvYxgroqmASyhtycQCLU2+gFUwazq596uYdbqDNWAv8jzYgfYc/ijEKyp1vmNnv2U2X/c+jAFydW2vo/se8FULhNxaQedq9IaT7o4jliOBCcHAh3a6tK0TDRDZ7MTiGBC//joVC48mBDJ7MRIT76cv/6mztTxktmcAVLLAncUVdXjMcpaZKAjQoFNSsF7pso0UEqJULlmQRphC8d7GsxRWithfU7Kh/La69lUwJj1boLCAQAJ+BqUH8FlREhtJbLQlmsAyamYyMH79yuHugAaDdgtftcrvYafY2IY9gXG1sAjkQItYQzbuIneQYrcIo3qyJuT5UnqsCd8WqXu0qS15v3+vqBjv9rFd/kxISs2BOfWnH"
  admin.passwordMtime: "AgBJUJgaGhVAx4b4sqd/SFS0nh/pzpw+qmuEafozA/dsQIQaMSwF6l8LH4czynpNSzIjmOSuKnL58Wfv8arc2mZMLMdDEiFYJaUpsyKNM9HEBMiHuGBMtrXsEEG6/Ionwsm16Gc7IrzKhf6wbjSB1l3yPModgnjM1x27v5uWlN3R5t8UA7DFw4nDOxL9V6bn8QQW9dtwnAGIElI4tlKzgLjKmSUyezZwBr+nzITl7duFpGk36kqF5xZOLjGSl1QkG0Z8cDwCsRY7+cU+POlXImAjKMD9XP9lX29zea7qMSZ80LMHeGeb6S1bgbw1PDkFp/uyYvPZxvyo3W+wqnXtFYOCTcCLGM94Uh81Jci1Wc2qctxDjY2pu5wj9E9ZBQ19UuFzppBpZp9xSVl6M5eh/y0ZzXISZ+GRW4DwE8UlgpPDrh1laSXfwqyCpJYMd2hJuJ7fs9IUVw7laoYak1/HnNNK4HmsDZmrWeTjzZ2/PtkjEWgBeOkFoaSg1nzqw9zth9nja0YMWF75Ohe5uL1TxcLSx2mb2exwMvgE23nUM23lnINEoVO2tYYqMILflklV6PxQBYDbqgW7zub5sW6nGKulNBhRazrw7vHKWoA8Z3XFQfZ51uNCSXWL/PRcduqG5cWCLh/yAfJ0ruYpDIfHCWEXCeTcJsJXTmBWUgacpPa6OW9E7gHdzdz+3ZS1fFfP9lw61CaI4n5SRJMm0bXlWH3riXWvBdo="
  server.secretkey: "AgCu4uodWpAgOHLFlZ6dqihrz40INtJE9p/hhlhOzcgiezqVP4PQpS/G4nAR9gFy0G1IB9JqbHrGHGE99EH9cPXSyKM4x4k7x5BX1GriIW6Stg8926pFe9k0PulQk5zG/Tt82mKAdfnaehK5qvPYxcUUpQ2KSq7J60mBFy6uxovth3n1Ti/gb2Qf5OJW70GCT4wJXZatni6NxkgkLC86qWkNsvRghV0dvvmdzuQ67Qa0Xj7mdG2cbDMl1yn3mvWqZDbVqeod7aKlzqtFea/4htHLoUbTySmeBLpChNoYJlSZfuUTmEd6B6JRk0P5xAq/leOUImRT2qxGPzV7fIkmm+XAqhf7NPEob67CMoMj9+C9aL7ogZl2SIBUV08r8w7SeOrHGODilvm5OSbWEdiPCkLvoQWUGYyaBRPUrcgnw9FXALbja+TAIT9gL6MoVNLMWbqn0Z4b40kP6GM0kb5/HPe7H1rx/mZL+obNR4LLrCVSSI2Z2ofri9LG6P3fKJuJ6AEve4O9hviKTvRcohxc5nczm9Mky5gIaMCGlZoNP3F+36xufS/gDWHDfLUpe3Pp9EFvU4FpLGyOlYs5Rt1x0Djxg90sRN237OClV29e1fVnztOWUWxyqiB5BalTBTWcriFzOtlunNceS2o62l1zs8ih8kjlR16ow2zIlRdmEQ7yvR7tLJIc9/3FGkVl/Mqi0GOvxGd13HVYnqKdCpo1vExp/gdgvmjPK8Pv"
defaultRepoUrl: 'https://github.com/aeternity/gitops-tools.git'
defaultTargetRevision: dev

applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
  aws-load-balancer-controller:
    project: tools
    namespace: kube-system
  traefik:
    project: tools
    namespace: traefik

argo-cd:
  configs:
    secret:
      createSecret: false
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      pathType: ImplementationSpecific
      hosts:
        - "argocd.dev.aeternity.io"
    extraArgs:
      - --insecure=true
    logLevel: debug
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.dev.aeternity.io/
      # Argo CD instance label key
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - url: https://github.com/aeternity/gitops-tools.git
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
        - type: helm
          url: https://helm.traefik.io/traefik
          name: traefik
        - type: helm
          url: https://prometheus-community.github.io/helm-charts
          name: prometheus-community
        - type: helm
          url: https://aws.github.io/eks-charts
          name: eks
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: aabbccddeeff00112233
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: aeternity
      # oidc.config: |
      #   requestedIDTokenClaims:
      #     groups:
      #       essential: true
      #   requestedScopes:
      #     - openid
      #     - profile
      #     - email
    additionalProjects:
      - name: tools
        namespace: argocd
        additionalLabels: {}
        additionalAnnotations: {}
        description: Tools used to run the environment
        sourceRepos:
          - 'https://github.com/aeternity/gitops-tools.git'
        destinations:
          - namespace: tools
            server: https://kubernetes.default.svc
          - namespace: argocd
            server: https://kubernetes.default.svc
          - namespace: sealed-secrets
            server: https://kubernetes.default.svc
          - namespace: kube-system
            server: https://kubernetes.default.svc
          - namespace: traefik
            server: https://kubernetes.default.svc
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
