apiVersion: v2
name: kube-prometheus-stack
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.

version: 47.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 47.1.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: app-secrets
    version: 0.0.1
    repository: "file://../app-secrets"
