app-secrets:
  external:
    remotePrefix: /k8s/stg-m4n4

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: redis_exporter
          static_configs:
            - targets: ['192.168.1.111:9121']
        - job_name: node
          static_configs:
            - targets: ['192.168.1.111:9100']
    ingress:
      hosts:
        - "prometheus.stg.aeternity.io"

  grafana:
    grafana.ini:
      server:
        domain: grafana.stg.aeternity.io
        root_url: https://grafana.stg.aeternity.io
    ingress:
      hosts:
        - "grafana.stg.aeternity.io"

  alertmanager:
    alertmanagerSpec:
      externalUrl: "https://alertmanager.stg.aeternity.io"
    ingress:
      hosts:
        - "alertmanager.stg.aeternity.io"
