app-secrets:
  external:
    values:
      GITHUB_CLIENT_ID: /monitoring/GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET: /monitoring/GITHUB_CLIENT_SECRET
      GRAFANA_ADMIN_USER: /monitoring/GRAFANA_ADMIN_USER
      GRAFANA_ADMIN_PASSWORD: /monitoring/GRAFANA_ADMIN_PASSWORD
      SLACK_HOOK_URL: /monitoring/SLACK_HOOK_URL
