app-secrets:
  external:
    remotePrefix: /k8s/prd-0e9c

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: node_exporter
          static_configs:
            - targets: ['172.16.4.210:9100']
    ingress:
      hosts:
        - "prometheus.prd.aeternity.io"

  grafana:
    grafana.ini:
      server:
        domain: grafana.prd.aeternity.io
        root_url: https://grafana.prd.aeternity.io
    ingress:
      hosts:
        - "grafana.prd.aeternity.io"

  alertmanager:
    alertmanagerSpec:
      externalUrl: "https://alertmanager.prd.aeternity.io"
    ingress:
      hosts:
        - "alertmanager.prd.aeternity.io"
