app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs: []
    ingress:
      hosts:
        - "prometheus.dev.aeternity.io"

  grafana:
    grafana.ini:
      server:
        domain: grafana.dev.aeternity.io
        root_url: https://grafana.dev.aeternity.io
    ingress:
      hosts:
        - "grafana.dev.aeternity.io"

  alertmanager:
    alertmanagerSpec:
      externalUrl: "https://alertmanager.dev.aeternity.io"
    ingress:
      hosts:
        - "alertmanager.dev.aeternity.io"
