app-secrets:
  external:
    values:
      GITHUB_CLIENT_ID: GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET: GITHUB_CLIENT_SECRET
      GRAFANA_ADMIN_USER: GRAFANA_ADMIN_USER
      GRAFANA_ADMIN_PASSWORD: GRAFANA_ADMIN_PASSWORD
      SLACK_HOOK_URL: SLACK_HOOK_URL
