app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7

alerts:
  platformSlackChannel: 'alerts-platform-dev'
  blockchainSlackChannel: 'alerts-blockchain-dev'
  appsSlackChannel: 'alerts-apps-dev'

kube-prometheus-stack:
  prometheus-node-exporter:
    resources:
      requests:
        cpu: 50m

  prometheus:
    prometheusSpec:
      resources:
        requests:
          cpu: 50m
      additionalScrapeConfigs:
        - job_name: sd_node_exporter
          ec2_sd_configs:
            - region: eu-north-1
              port: 9100
              filters:
                - name: instance-state-name
                  values: [running]
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1, integration, next, uat, uat_mon, api_uat, uat_backup, main, main_mon, main_backup, api_main]
            - region: eu-central-1
              port: 9100
              filters:
                - name: instance-state-name
                  values: [running]
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1, integration, next, uat, uat_mon, api_uat, uat_backup, main, main_mon, main_backup, api_main]
            - region: us-west-2
              port: 9100
              filters:
                - name: instance-state-name
                  values: [running]
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1, integration, next, uat, uat_mon, api_uat, uat_backup, main, main_mon, main_backup, api_main]
            - region: us-east-2
              port: 9100
              filters:
                - name: instance-state-name
                  values: [running]
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1, integration, next, uat, uat_mon, api_uat, uat_backup, main, main_mon, main_backup, api_main]
            - region: ap-southeast-1
              port: 9100
              filters:
                - name: instance-state-name
                  values: [running]
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1, integration, next, uat, uat_mon, api_uat, uat_backup, main, main_mon, main_backup, api_main]
          relabel_configs:
            - source_labels: [namespace]
              target_label: namespace
              replacement: 'aenodes'
            - source_labels: [__meta_ec2_public_ip]
              replacement: '${1}:9100'
              target_label: __address__
            - source_labels: [__meta_ec2_instance_id]
              target_label: instance
            - source_labels: [__meta_ec2_public_ip]
              target_label: public_ip
            - source_labels: [__meta_ec2_instance_type]
              target_label: instance_type
            - source_labels: [__meta_ec2_instance_lifecycle]
              target_label: lifecycle
            - source_labels: [__meta_ec2_ami]
              target_label: ami
            - source_labels: [__meta_ec2_region]
              target_label: region
            - source_labels: [__meta_ec2_tag_role]
              target_label: role
            - source_labels: [__meta_ec2_tag_env]
              target_label: env
            - source_labels: [__meta_ec2_tag_kind]
              target_label: kind
            - source_labels: [__meta_ec2_tag_Name]
              target_label: name
        - job_name: sd_statsd_exporter
          ec2_sd_configs:
            - region: eu-north-1
              port: 9102
              filters:
                - name: instance-state-name
                  values: [running]
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1, integration, next, uat, uat_mon, api_uat, uat_backup, main, main_mon, main_backup, api_main]
            - region: eu-central-1
              port: 9102
              filters:
                - name: instance-state-name
                  values: [running]
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1, integration, next, uat, uat_mon, api_uat, uat_backup, main, main_mon, main_backup, api_main]
            - region: us-west-2
              port: 9102
              filters:
                - name: instance-state-name
                  values: [running]
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1, integration, next, uat, uat_mon, api_uat, uat_backup, main, main_mon, main_backup, api_main]
            - region: us-east-2
              port: 9102
              filters:
                - name: instance-state-name
                  values: [running]
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1, integration, next, uat, uat_mon, api_uat, uat_backup, main, main_mon, main_backup, api_main]
            - region: ap-southeast-1
              port: 9102
              filters:
                - name: instance-state-name
                  values: [running]
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1, integration, uat, uat_mon, api_uat, uat_backup, main, main_mon, main_backup, api_main]
          relabel_configs:
            - source_labels: [namespace]
              target_label: namespace
              replacement: 'aenodes'
            - source_labels: [__meta_ec2_public_ip]
              replacement: '${1}:9102'
              target_label: __address__
            - source_labels: [__meta_ec2_instance_id]
              target_label: instance
            - source_labels: [__meta_ec2_public_ip]
              target_label: public_ip
            - source_labels: [__meta_ec2_instance_type]
              target_label: instance_type
            - source_labels: [__meta_ec2_instance_lifecycle]
              target_label: lifecycle
            - source_labels: [__meta_ec2_ami]
              target_label: ami
            - source_labels: [__meta_ec2_region]
              target_label: region
            - source_labels: [__meta_ec2_tag_role]
              target_label: role
            - source_labels: [__meta_ec2_tag_env]
              target_label: env
            - source_labels: [__meta_ec2_tag_kind]
              target_label: kind
            - source_labels: [__meta_ec2_tag_Name]
              target_label: name

    ingress:
      hosts:
        - "prometheus.dev.aeternity.io"

  grafana:
    resources:
      requests:
        cpu: 100m
    sidecar:
      resources:
        requests:
          cpu: 100m
    grafana.ini:
      server:
        domain: grafana.dev.aeternity.io
        root_url: https://grafana.dev.aeternity.io
    ingress:
      hosts:
        - "grafana.dev.aeternity.io"

  alertmanager:
    alertmanagerSpec:
      externalUrl: "https://alertmanager.dev.aeternity.io"
    ingress:
      hosts:
        - "alertmanager.dev.aeternity.io"
