app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: statsd_exporter
          static_configs:
            - targets: ['51.20.2.29:9102']
        - job_name: sd_statsd_exporter
          ec2_sd_configs:
            - region: eu-north-1
              port: 9102
              filters:
                - name: tag:role
                  values: [aenode]
                - name: tag:env
                  values: [dev1]
          relabel_configs:
            - source_labels: [__meta_ec2_public_ip]
              replacement: '${1}:9102'
              target_label: __address__
            - source_labels: [__meta_ec2_tag_Name]
              target_label: instance
            - source_labels: [__meta_ec2_private_ip]
              target_label: ip
    ingress:
      hosts:
        - "prometheus.dev.aeternity.io"

  grafana:
    grafana.ini:
      server:
        domain: grafana.dev.aeternity.io
        root_url: https://grafana.dev.aeternity.io
    ingress:
      hosts:
        - "grafana.dev.aeternity.io"

  alertmanager:
    alertmanagerSpec:
      externalUrl: "https://alertmanager.dev.aeternity.io"
    ingress:
      hosts:
        - "alertmanager.dev.aeternity.io"
