encValues:
  github_client_id: 'AgAe0p2n049c0n+6zgh7PO+/wbqqel3fHVbluyREzLJ1KvJunEuViMZXUlnOYHYvZ+2Edg3fROEr6eupYmiMeNbi970HxbdmTgJTPqw7zYn07QfacDYvtSr8ste/WwTim/ybakHI2aWYalDNCtEy7js7GceR0qTjBIF/F70udsCmHNSx+TEEWG4geGxHVg+xDRqGQ+L5pbPrlLH7PP1fUXy7jnz34KEA9/0hAE58A9oxcExYh+4zAx34pZAoFvQspuMABejxU35fLOAzBwHKcyCBNxF+GpUmFlAByXUc5pbnqHkxIKUmJB5gw8ePZd2rd3fyhmLUjC9JQCRVUkRoRikAXfAb8kMEcJ7LoAfQEuVeGIvfO14WrtJ9MCVYBA06YF6/o9Rrf/xeZUREnqz0MSE5qpY7xHOLpnVJt5NeQ/OB9VHW9c/SUOPNk+769/bVqgI3bBBFeRNbwS7SjrsW5tzAuK4/99yWAG3rwEfydvC8G/GWh/I0lu4mJtDS5Hkr2EFjD9LDgV/y/p47h6lDQPxaerf8nrSr6tsS1I8Xs/4k4En19BArJr85JkWK/5Z+APWchiweQYnhhTcKGboWULc7WHL6y7euRyEzBsnqv9bfGgPICfx2ZtlZ8CEME3YrURUgnvALSpkkuj6RDwdSZIeOJSM/BA7LjTzhUOMji+5Wjar+apHQ1LwRbJEydXuTfO8nrBgxKzbFGQQrbndMUdonq17t6A=='
  github_client_secret: 'AgAVMu6FM6vCxHXIn2TfLk3hqcZXE93j1v8W1lPloIKgpgOUuFxHwogwqsf1G8TtT6fUY7WbKLjm1zHUeI2BsVU6bOE4xl20TXPqBdLS/uR5bm+0WS9v45zoA/lY7U3/owdg27T2jLEq6u0LmmlQCadPYu6YLxtZgvMdrsFrfB4xQAjukT7D5IUuX0QT+64n57za190foDst1WMpzNk9IMcwGWY29C8v3CURYIvq+ecmSTWmU+jv71Ec42Rp0AeXWHUVjLAt7rLy2N4xYBxCDOvFGetfwkO0zNAmOXb0QXEYol3oAbkagcKY3UrozJ1j9QqGqBvGlcqNEUjnwAzDUWqZbd0WSdduX2O0nADhkLkxx7lrJP8zGzycSunz67UIe2rRWElxHyejfUW7WMiWyfFzY+rE/b4xXOS+hOjriAC/VeoNq+zLu50rbpKSfhLKBiyV+Ykb9bCFiiuPZHJcW/5svR9bHQOHvGeMlTNi0IoBKmHHr5EZkXB6dPmSEryK6Bzu/WQFhrbPT5FNKDLm0/t8hO1klVfmwU273P+ayA67o3/wc9SdVnAOigsgcmmo62uqevb2VvE+hgKHWt6DdAqMuZRgCaIXWTC0xmjvQCUG2wlhBp2EAXUVsRR0awJIwzOeH/1BVb1PUujuE8jrvU9TMpBkqmnCVR72ijpEHHp6txrTOiwAKklR+a4DqRHuOg4GZeUQ1FWCRktAbORhH+0mjClFQmgBV8LaMUCy0ejOhFjWyHVlK6qc'
  grafana_admin_user: 'AgCXAQ0ATSwiY5520fiuvrRVzWRUPjZsp7UKVPxeZO6nHztf5TKd4hN1zL6gEHwqzdYS/vB9ZDv2MUJOvtNNCYgU+uQkIVpV21lBp3sWxsCsCbh6h17FuTPhAlcPDPYsvLWBvtuWbVj51DmUvnfi8ySy7AQ57hlpKcrGHczyTpvU0muNHmNw+LX8BHCKlJzj6/Wd9MZbiTNuzhRz3QtODFhpBmyQnL4OUgI1m4u0I7iV8SjYuKE11p9oZrASJMJuH3YL9uWcWYLvjVj/RAch9fwK5wilD4Pfk+jT85r2tENsGwCLDi7n0tZVPoei1TELxXzZHv/bj3D36P6yp9pHC/3JKe+nlHAf+bvcZXr71U0+Fi5eyzbHpunteXFi5ZbSvWe2G5Mi+9BQMuCMZxhD3kTDVRAN0s0AJkjw4e0zJxwt1WyQcVDcAb4R79KYcDygdoOE1ZW32d3Ij+UMX13LoyD1k8mXu0LVrWhVOThzuejmBsotjq+VbqSPXoVUpxFg9N0i0q7fmh50kihFpVF6U1COnGYIanTMwCX+HXOFJP3Bp4eTj0u7rObNkLsgBZBzslRDcgbshc5Pa24nfbMQubKRx39H9Z1Nzz7i4P7qKtlt4WvxvxrXJcGetL1FMlmUnuTnPDpKkfMmakSdum4OJW1E4Vv8OkJ9RgWEh9L1AV58ZaLb5IhA/gpT/HnviPsVQ0UBJjsklg=='
  grafana_admin_password: 'AgAHW13ga8iCw26UMAg9z4SUyuR/KQeh5/HPZ+NSeyhgk3PjiroiobKm1s0pu63Gx3eR69mKk2oOVplDL4n2buZgT1us0oVw4Fa4hH2mBXkgJd3Riy54vCSv1Bmakoe6nKCx1Uh8as+dMNjNkVl8kzb5YYakXY8J1Z+yHOo2+j7t+KxS0YKjHuJk6BsCPjw96kMog0iMCu3rC38DVk/+mPydD9mLg+NUbblENvTozT0VfiXpOSPgyL+AGOYoZ6L5qlNlWGdUOKu6lc5+ynoRhJJmikHmz53R5c+RhJBDhy72NuqPN6MRZfVEaQYd7DPlsEIOdlVo8oFSSKhIlj1UY4JtiADpsBzIr+yqZ+NsRRKBrZUqWZOLiakmx35jf6Nn921v3K+DpTmsJn3/QNkdpPIS/9Qj1DBGKBXw8kNZtTs3Kn7+hG5CkssRcQq4s7B1W4Q/kmjJxniUutSPYsHLtk642UT1aDCno7UPLRcz/vxcq2jaQfXVrcF5Pp79wWKkjq/DRri/pKTSATRKvSGwYJBYkglnfn8N3zVTcegjzxq0lThmSaG7bQ0wG16iuChxT0UwbZ1VagsDHK1+uca6GMrh++KJNXNSm7xolOsOWXkOWiH30gkLIgzJhhZ8fiyR1C16MQksMKB5BgxKc9DWm50Lqizl0UzN4XGMlgkMXN5+jGF55n9QMUURI6DkzYtlKFM/KCGlz1fXVPJ5EwYqadkFyGM='

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      additionalScrapeConfigs: []
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - "prometheus.stg.aeternity.io"
      pathType: ImplementationSpecific

  grafana:
    admin:
      existingSecret: kube-prometheus-stack-secret
      userKey: grafana_admin_user
      passwordKey: grafana_admin_password
    sidecar:
      dashboards:
        enabled: true
        folderAnnotation: grafana-dashboard-dir
    grafana.ini:
      server:
        domain: grafana.stg.aeternity.io
        root_url: https://grafana.stg.aeternity.io
      plugins:
        enable_alpha: true
      auth.github:
        enabled: true
        client_id: $__file{/etc/secrets/github_client_id}
        client_secret: $__file{/etc/secrets/github_client_secret}
        scopes: user:email,read:org
        auth_url: https://github.com/login/oauth/authorize
        token_url: https://github.com/login/oauth/access_token
        api_url: https://api.github.com/user
        allow_sign_up: true
        allowed_organizations: aeternity
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - "grafana.stg.aeternity.io"
      pathType: ImplementationSpecific
    plugins:
      - grafana-piechart-panel
    dashboardProviders:
     dashboardproviders.yaml:
       apiVersion: 1
       providers:
       - name: 'tools'
         orgId: 1
         folder: 'Tools'
         type: file
         disableDeletion: true
         editable: true
         options:
           path: /var/lib/grafana/dashboards/tools
    dashboards:
      tools:
        traefik2:
          gnetId: 11462
          revision: 1
          datasource: Prometheus
        argocd:
          gnetId: 14584
          revision: 1
          datasource: Prometheus
    extraSecretMounts:
    - name: secrets-mount
      secretName: kube-prometheus-stack-secret
      defaultMode: 0440
      mountPath: /etc/secrets
      readOnly: true

  alertmanager:
    alertmanagerSpec:
      externalUrl: "https://alertmanager.stg.aeternity.io"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - "alertmanager.stg.aeternity.io"
      pathType: ImplementationSpecific

  defaultRules:
    rules:
      kubeScheduler: false
