app-secrets:
  external:
    remotePrefix: /k8s/prd-0e9c

kube-prometheus-stack:
  prometheus:
    ingress:
      hosts:
        - "prometheus.prd.aeternity.io"
      tls:
        - hosts:
          - "prometheus.prd.aeternity.io"
          secretName: prometheus-cert

  grafana:
    grafana.ini:
      server:
        domain: grafana.prd.aeternity.io
        root_url: https://grafana.prd.aeternity.io
    ingress:
      hosts:
        - "grafana.prd.aeternity.io"
      tls:
        - hosts:
          - "grafana.prd.aeternity.io"
          secretName: grafana-cert

  alertmanager:
    alertmanagerSpec:
      externalUrl: "https://alertmanager.prd.aeternity.io"
    ingress:
      hosts:
        - "alertmanager.prd.aeternity.io"
      tls:
        - hosts:
          - "alertmanager.prd.aeternity.io"
          secretName: alertmanager-cert
