encValues:
  github_client_id: 'AgBSNNKZ6mwri3zNJJqrI3Kfydynw+KwsvTIMxy1/vdQMZPRMqm+WZzlkTom6/ibkoTrHNZq4+Lp5YMupBVoMDqa8reaCrfQ5UZB9eROAzlGgeMxCob90p/tqrM4V+hE4+iaJwNjgETknR2d58pWukfML78FOIV+Bow23HTC79aPXvUm3XYdNWJKjAE9hW+hJ7LbgHF38fH8LvkpRfafRbN80mGabg8oOrIrsDsSq5LFkyDBKUKCY2XjKZ4bzGSu9cZSmG66P6swooBqWJdIA7UFtVDicLppRCYbChLHxjv/dk4y1OTfLkov7qS0h8JJE+P/QWc8nRU5FDL1gN+3UdHdEJ+ay5BZD57GXPmjj3uko0iRfuBGJI/z2QY90/gB4rZVgYEg8fa6AVh48qjo84R1CvV5uh9/BVFAcHBtnc/EDA5Uz83GjQfCsrX3TSsLPJJxA4/elDqybjnEW79Da8Hwx+2x88JAP0KzubD1b0WsYyMNAjcLgOWL75qU7YcPqQbEu0HA4/JeAZcY2XojTzlBe63cBhjA629baK9aGhRfZtzXDxrBaRfTsJ09To3j8yAYhalD0wP3iK8nK9RSuCsprumkZQVF4j2r3NXrAbvGUUjKUEHk5YhP31NfUwrpXX17hn1q/Vg4yaq1rO5VYPZ89U6NtIySizx1+ZWMrEHQFYFVCq2VqsxVZftSqFeUm2ILtKGp8B0zlD5574FlkqkVt6i38cM='
  github_client_secret: 'AgCKtJuJTsbc6bX62TMFAvt+sLxWA1MyHlnSwnbGDLXnjjD+ogV6sc5pa5krgEHV/iuG6Kw3Z/C51U+S5nH9xN2UvIDxlgPQQrtOkLceeiz1dmRVECTkl+XTnyYZdoXzd38BMtKDJp6oHaozhDlgi0D45WZRxFIJi//NWtfjyFexpJzKhnKrrFpYlosjybTrAiV87IQD0T0PVjamxbC3Tlmh+jQxQEBUixSaYh60wSyB7SfmE82kdowUDBwY1OPP6xJj7c0mTsB5vYL7AfAXu3rhaK0spXxLwxO5Zs0I0k/++6Uv8EUJVt2THJNe49vcyUs1pTzzK4Ck0iQ9k0VvAR8y5x0iqnlfRx/0vn38M2c+ngi/nne6gHGEZ4mKWgXuAD3R6PoDW/jG4WzcVkn/i+1rdjf+hWpEf9ff0BvVvmEtZS/mp6rlcyAiRmWQwDJlQxBXqO3b4aKD2YBUlqL7kA2eqn+hGlD+Rd5deyAHXcmedbIvgW+VFXLCiDu/je7kWYhS62lN8hzrWyprrTsnZPWZVSP5wxOVXN7KoUrQOyaO4gFYQWnP9Y+VLz+wK3RcQcO3/i/qQUfIRU+GIwNt55aDqsyiwpbp+Viho5L0NS92Nq089dmf/wfRRMUOhUp4v0gk0FgHgDcfgutsnc5/TerHKyuV9Xp7EppA64kXDoc9bofpDYXKcl/a286XntjPHm8DNE8tDuvEaLxtXk367Z8TpG6b5U2Uium08ZYKn9s3OP9iDSzSaiZkKw=='
  grafana_admin_user: 'AgApWxtCQJCqwjQpi9W66GNljxmagSz65pbLAvHCinIy6JNWvXvm8FVIGGCbBhcqG7BrYLRJ7lALvEVmYzHcrcuVUsJsrBSji4sGCJGoTbhJLbPgZRTjzFaOHYkZGJdCvuu42B9n+3ouIX4z1tZjqCs8YyoOVxFmAOg6Q9sSBlvK4ztSzeBPXutnkO/fRUCZmQHi6ToYTekgmS+aFreLL68Hm7Q1iuRYSpo/CpIMpe655GFs2mM82wxAURHAHR7cOcRKgfWajj9WG4xywWcnxOMubYUjG3gqGCXdXGqT95Fot4yWYxnFO27rvGZsa6fJarwwECva32NhqdKzALBoS+ZPlBtcBkvnKH6qrOgz4TUMHAN6ocOiHobivDZ7xbyk6oHJvK8rOj0DnwFms6iw04/nmCg1eONM9Kd7Y1SpdVDyfgEEeGEDAevPsNUVyPbab0/U02sA+ZSWW0pOH5BzD0MkZF7WMaeZNpICP7KqesDQOlFNH8tf2yjpn2dhxI5Z0iFXfafs294oRim6d19SOKTeyO4vaZ8gZQemmcGtP6OFT16BPObQUUZ0TD9nR5c5313X5F21U7voSJjqn08eh80Y5qLAoLOG2p8hwdxa5QIK++OL02yChj+F0hIfsHT+OwB8Q+yXoO1mZNiIsubDCKmuTmf7+ryO4NJ4BSkm+2I3OfQ8erQmis+TBSPcvzEx7PcAHuglJvU='
  grafana_admin_password: 'AgAWogroq3PAP5s7H0RiFLIxITVuywzT6CjDpUgvK+f3rXRredxWbAnM+isHAdw4hy65CAX7l5qyHKOhX3tI3ephtpt43OwtuxRHt53xUO1uNFbjEUr28GvlV0aLnP4zFUqF7EW6wocs4gWhwG1rX+06S7PVOSN5QzeYlibbqsQc7kbmLa+0J8nd9idRfr2V7w3+2AvmPvACcuxumciQg01NCL5TnZaFolWWtx7pqCBJ7WfaeX+SiPuQT64u14RUbwDxHiCqfgEkTxTrclydUcEQbLrk9GzY4J+MTJDJSp2iNGC2Bjx7tuRDi1WWuw4hJK10LcX4w+7GeUuZI1Zksgyl2UK/GvoON5Lf+j8+Wz0UyCLsZ+8G5IRLG04TEBxMs4RNH8isEn2DW8JZiDAaQ/djU42/xnajj5t+0OBQS99RWk6B/nEBEdkwTOvlaq0b1m9n8307zKV1uGQLxS32LF5//ZlCgS78sdejEfVvPVnFz3QOZpt0BZ+tsg5JoNcHhFNpfpW84/Jujh5pxQlkVSLvg9R9CPCRx5sHmAftFBdaQOpzb7jY870zxZVDG/AmIxiAV3hbYR2UuPT1D1T35NnhGCFvE38aotHQxq2kLXhFjBWrTTNNsye4Jpdq0xTe/RP2rkY3mFyn+/XS0DISsXIHHGnYEcNkHRbxv11+7pZNp+EEydscXFx1qIXunSc9sbaVOtgoezhRqDGcS9I15sKsuVXGbc3sgB301wvuzV9LlWM='

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      additionalScrapeConfigs: []
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - "prometheus.dev.aeternity.io"
      pathType: ImplementationSpecific

  grafana:
    admin:
      existingSecret: kube-prometheus-stack-secret
      userKey: grafana_admin_user
      passwordKey: grafana_admin_password
    sidecar:
      dashboards:
        enabled: true
        folderAnnotation: grafana-dashboard-dir
    grafana.ini:
      server:
        domain: grafana.dev.aeternity.io
        root_url: https://grafana.dev.aeternity.io
      plugins:
        enable_alpha: true
      auth.github:
        enabled: true
        client_id: $__file{/etc/secrets/github_client_id}
        client_secret: $__file{/etc/secrets/github_client_secret}
        scopes: user:email,read:org
        auth_url: https://github.com/login/oauth/authorize
        token_url: https://github.com/login/oauth/access_token
        api_url: https://api.github.com/user
        allow_sign_up: true
        allowed_organizations: aeternity
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - "grafana.dev.aeternity.io"
      pathType: ImplementationSpecific
    plugins:
      - grafana-piechart-panel
    dashboardProviders:
     dashboardproviders.yaml:
       apiVersion: 1
       providers:
       - name: 'tools'
         orgId: 1
         folder: 'Tools'
         type: file
         disableDeletion: true
         editable: true
         options:
           path: /var/lib/grafana/dashboards/tools
    dashboards:
      tools:
        traefik2:
          gnetId: 11462
          revision: 1
          datasource: Prometheus
    extraSecretMounts:
    - name: secrets-mount
      secretName: kube-prometheus-stack-secret
      defaultMode: 0440
      mountPath: /etc/secrets
      readOnly: true

  alertmanager:
    alertmanagerSpec:
      externalUrl: "https://alertmanager.dev.aeternity.io"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - "alertmanager.dev.aeternity.io"
      pathType: ImplementationSpecific

  defaultRules:
    rules:
      kubeScheduler: false
