encValues:
  github_client_id: 'AgCuWI0n7cGIDx3e+sz15x3JnR7hbjx4MePyWEKaQy1AR0xfCtCmOYsr5pTuPkKlUyozyQKhZ/eHrdPio5FQWWQqZtn4OZfNmKuCUtcEtcZa/5k6AbYe13W5m8UsWB4wYR4j7zfUxvE80+LpErw08BkhqtmGBiy0ub+QfrYiwCsoXb0XWD3H3qKQxNsL57iq9Id6b3GHtY1ZuBhLS+GdOfjHWbMjq02bM2dNSULvK26mkALqjieUqRTtubQcXhENrV9VvEMEOAQRF7L4eViW67pGeWcklLwx/dBdDDMfcWoUFW212cp4TLittnetVjeuPwsRpVl912I0QNDhZymi7hRj/xw4C1+/zclgmlfeVLuRFORgDK5e0EiVdDAeg5Bi4LfBRGu/RoBg1lR2rdp54uZIYBIWYH9sFK7YgxhD0SVm8PUNGbC8fJCye4KHir32y8iIhM/fDIx0CRE4QR2yKhpKAFcOgWG0Jlmh0ZHduJCnWv2O/cBXWeZ6Yujs0uK6lYLjGGD5jqlyF6BVpmeS3IAojbVMIlbzsxKrwlKTp9a7jF223vSiC0GRkMTcKlFJPPJhOjkgk8FQoL31nO2RgKHuLMVqe1DDdf+sIH25Xj75eu9aP51eq9XoxFdaytuym9AzjxEq4C8CInnMlb/ZtbSnFZigvBf+ym3W+CwUJktFQWdwDUB7DYmd1lJkK7XEY5TMZX8ewAX1cb14p2o2H43XZN2EKA=='
  github_client_secret: 'AgA2rCzb4qfDfQtefCnB2o3SWJPUfH4KiKVBMJNblo+sYfcaqpUcqP9RHiCRLGcDaQlwo4zTp/IFSoYIc/QJiEKNCNzvgXHtSV4mKsWcxqAkE0bOR1+ynlSvb647ekgH/J3aVd8M13XHoAS+08b8gzVTfHlaimTnds8/E428pk72qglKSt6DGfklvy3zQyAizsZ0zGFnlr4sfAvuKSCJoFI4YkrhUxxnBG/sP3wBvxh4TGRO1L4PsW39OJnGG9h3FgN9bkHz1T6pBuMzlTfVprbnEJ1RIAjfi3snX4He+u+5jQhwba0ykLJde7lZJDCSrIATRnpb5ybceWgoi7ItL8oEDAHKy2guoFHV+pQ+G3VIm/mNC60sVme6BE5eKSKzbumZlSlu6/jvtgMBJfJJVaBUkBe/pv0p44EvahFwc6os1E3LEMgPiQnWjuSKXkhL6eSw6/OrJVOGvSBC3ym6bvjQMCV1fFEFaN87AWXDUkMchivgZzUd+G1NZ8hA8rMSejVbW02fAk2KnRynzkoo2juRlFY5mAR+IZcXFFmb6dq3FJ93PjL/oMjosrPywv1qDiun9SUaRsWh8a+wGPR556oRbvSspGf4aW99S0sk9kOWVVEo6ovI2sy60rARmInF39JNbxUINS09K/oIGzW5l5eItHrSz2+pNuuafzjyreXf9JvtXgmtnYilAsema+eAwElBoPQymzOyrMD5K0BCcZwe0odzkWLpceEfZmgUvKM3zkmvrFrfZ9Kq'
  grafana_admin_user: 'AgAAq18+/XbcNNE6eBPNbN1Lr5EhKlQN7vlih+rCX+MYTG61eWpNlQ6UWalfaJfsNU3Qxe0W0G6TyjuRSCHBypbHIUqNPSb8Udo9Rxd365SxLsUX2U79uRq48057dVq63PhHw0oDmoV/1sZ8A3e7nl7uH1mLnz7jSy0tPAJSVM4OAUQjdcKgg6VGY+sWl/X0IW9k7X+AjC0hAOKxjU1g999NwKG//Xlr3Hmre/FXhfLf3lZk9S5rIX2OlZrOg+bfJt+cRTfMYoAlZ1G4fCSI1YjxlY/BSGx4hpAERNGEh4typfdY4HgYa1LvXKhjxT4cMiSHv0rzVReP7dV/9eSCGdYFevma8Edgm10m0hhlLgEN+/escZD8t9qId+JaJDbr0PzvmleI3d8WA4+PzqszEOPA3P58namn+WZQTkWsr8Qy5fsQW5U9+Si7205sPovjSM8f/ZR1EMl99qwP4UCQRuRuuBshr8CV0D/YfG5uqkHr2avCq1rDjBhhJD2i5wBnGRWcFSgyqb/ag1oimf0+we4b28BsVE02OvLyOkAl4g3S75eZ+nNnyx9PjXXvbJbTg551p+IQN8sl5IeUJLQ4TzMFmpCPOAohKHlxIA8j+BoYLnNnXcLIfN819SXyalm2F0qs66qNss9bA1LGQjJbXe76+rSj5ntu8kIanJBmHcpj0CXHxBHV5iRo9vsXnvnguWa+h+5SSg=='
  grafana_admin_password: 'AgCR/+A8wvnn4w/IP2lfwKETlP365hOC6afYrjgcSB3J4ZOE9zSJmJ4fF603pXbYV40jSalPGPXjfvSktiMtOynLW7v0RVT70jc+AwPLYRLAV+J73IZIVa/X9BUG6ZBMo6uFbBDV8cXnUKpAh6G/+SAk4lBvuM/ALmL8nfDZpWUbxdKQ8nlI20TAaSnBIq6HM2E4UdB5j72FwI7NRQhrGg7QlwkkVj1hczunR15H+ABd0MOFFprDXIUjhZ8jjC+uV1HbqunkIaVxtqDrS+vJqPp9NCPggjZeHqNeUxpDnh0xWdNfAftRG5vrNGJPQ0scq+PyA24CED0bZBHvZAo75rwPaW7n8yxXNWa/UpPM9KYk3C9y66NirYa6ojbTHshgZnC4q6YmnlSppBId7u/rAG0Fb5C6UN/aLWbyN+DRapE8RGgGSnlLgYmWNGHPjmQePO852+Lefys4j6ZwqEiQBEGPOYnADDyZV0F4nWWRYYYUUrY5Fm9wLSGpi8lwhVCyAKMrXiOw1dN3Tf/43TfQl/El+A3jjx9BWtia6ambB5zyo8Y616vOsPv6WyPeS3Ae+ixwuin1f0iOaS5qpGxZJChXpnBJ3AXinNApwpdVIzuw/Si0at1HI+oWO3XIb2jwRTtau+JnyzkkOf3LMjqegqrmQ3GjRI5TFH0rsbVuCYDG3cb3CxnVzilRQPTNv93JeVLhK1tcZE2q7LE+9Fs5L8o='

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      additionalScrapeConfigs: []
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - "prometheus.stg.aeternity.io"
      pathType: ImplementationSpecific

  grafana:
    admin:
      existingSecret: kube-prometheus-stack-secret
      userKey: grafana_admin_user
      passwordKey: grafana_admin_password
    sidecar:
      dashboards:
        enabled: true
        folderAnnotation: grafana-dashboard-dir
    grafana.ini:
      server:
        domain: grafana.stg.aeternity.io
        root_url: https://grafana.stg.aeternity.io
      plugins:
        enable_alpha: true
      auth.github:
        enabled: true
        client_id: $__file{/etc/secrets/github_client_id}
        client_secret: $__file{/etc/secrets/github_client_secret}
        scopes: user:email,read:org
        auth_url: https://github.com/login/oauth/authorize
        token_url: https://github.com/login/oauth/access_token
        api_url: https://api.github.com/user
        allow_sign_up: true
        allowed_organizations: aeternity
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - "grafana.stg.aeternity.io"
      pathType: ImplementationSpecific
    plugins:
      - grafana-piechart-panel
    dashboardProviders:
     dashboardproviders.yaml:
       apiVersion: 1
       providers:
       - name: 'tools'
         orgId: 1
         folder: 'Tools'
         type: file
         disableDeletion: true
         editable: true
         options:
           path: /var/lib/grafana/dashboards/tools
    dashboards:
      tools:
        traefik2:
          gnetId: 11462
          revision: 1
          datasource: Prometheus
        argocd:
          gnetId: 14584
          revision: 1
          datasource: Prometheus
    extraSecretMounts:
    - name: secrets-mount
      secretName: kube-prometheus-stack-secret
      defaultMode: 0440
      mountPath: /etc/secrets
      readOnly: true

  alertmanager:
    alertmanagerSpec:
      externalUrl: "https://alertmanager.stg.aeternity.io"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - "alertmanager.stg.aeternity.io"
      pathType: ImplementationSpecific

  defaultRules:
    rules:
      kubeScheduler: false
