awx-operator:
  AWX:
    enabled: true
    customVolumes:
      postgres:
        enabled: true
        storageClassName: gp3
      projects:
        enabled: true
        storageClassName: gp3
    spec:
      postgres_storage_class: gp3
      postgres_data_volume_init: true
      ingress_type: ingress
      ingress_annotations: |
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt
      ingress_path_type: ImplementationSpecific
