fluent-bit:
  image:
    repository: cr.fluentbit.io/fluent/fluent-bit
    pullPolicy: Always
  resources:
    requests:
      cpu: 20m
      memory: 30Mi
    limits:
      memory: 45Mi
  rbac:
    create: true
    eventsAccess: true
  serviceMonitor:
    enabled: true
  dashboards:
    enabled: true
  podAnnotations:
    fluentbit.io/parser: logfmt
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          storage.path              /var/log/ds/flb-storage/
          storage.sync              normal
          storage.checksum          off
          storage.backlog.mem_limit 60M

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name                tail
          Path                /var/log/containers/*.log
          Tag                 kube.*
          Parser              docker_no_time
          Skip_Long_Lines     on
          Skip_Empty_Lines    on
          Mem_Buf_Limit       5M

      [INPUT]
          name                kubernetes_events
          tag                 kube_events
          interval_sec        30
          kube_request_limit  250
    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name                kubernetes
          Match               kube.*
          Labels              off
          # Safe some space until it's usefull to collect
          Annotations         off
          Merge_Log           on
          Keep_Log            off
          K8S-Logging.Parser  on

      [FILTER]
          name            nest
          match           kube.*
          operation       lift
          nested_under    kubernetes
          add_prefix      kubernetes_

      [FILTER]
          name        modify
          match       kube.*
          remove      kubernetes_pod_id
          remove      kubernetes_docker_id
          remove      kubernetes_container_hash
          remove      kubernetes_container_image
          remove      kubernetes_host

      [FILTER]
          name            nest
          match           kube.*
          operation       nest
          wildcard        kubernetes_*
          nest_under      kubernetes
          remove_prefix   kubernetes_
    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          name                   loki
          match                  kube.*
          host                   loki-headless
          port                   3100
          labels                 source=k8s-apps
          label_keys             $kubernetes['namespace_name'], $kubernetes['pod_name'], $kubernetes['container_name']
          line_format            json
      [OUTPUT]
          name                   loki
          match                  kube_events
          host                   loki-headless
          port                   3100
          labels                 source=k8s-events
          line_format            json
