fluent-bit:
  image:
    repository: cr.fluentbit.io/fluent/fluent-bit
    # Overrides the image tag whose default is {{ .Chart.AppVersion }}
    tag: "1.9.9"
    pullPolicy: Always
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level {{ .Values.logLevel }}
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          storage.path              /var/log/ds/flb-storage/
          storage.sync              normal
          storage.checksum          off
          storage.backlog.mem_limit 100M

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          Tag kube.*
          DB /var/log/ds/flb_kube.db
          DB.Sync            Normal
          Mem_Buf_Limit      50MB
          Skip_Long_Lines    Off
          Refresh_Interval   10
          Buffer_Chunk_Size  2MB
          Buffer_Max_Size    4MB
          Exclude_Path /var/log/containers/dex*.log,/var/log/containers/mdw-frontend*.log,/var/log/containers/superhero*.log
      [INPUT]
          Name tail
          Path /var/log/containers/dex*.log,/var/log/containers/mdw-frontend*.log,/var/log/containers/superhero*.log
          Tag nginx.*
          DB /var/log/ds/flb_kube_nginx.db
          DB.Sync            Normal
          Mem_Buf_Limit      50MB
          Skip_Long_Lines    Off
          Refresh_Interval   10
          Buffer_Chunk_Size  2MB
          Buffer_Max_Size    4MB

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match *
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
      [FILTER]
          Name     grep
          Match    *
          Exclude  log \"GET \/ HTTP\/1\.1\" 200
      [FILTER]
          Name        parser
          Match       nginx.*
          Key_Name    log
          Parser      nginx
          Preserve_Key  True
          Reserve_Data  True
      [FILTER]
          Name modify
          Match nginx.*
          Remove stream
          Rename method app_method
          Rename path app_path
          Rename remote app_remote
          Rename size app_size
          Rename host app_host
          Rename user app_user
          Rename code app_code
          Rename referer app_referer
      [FILTER]
          Name nest
          Match nginx.*
          Operation nest
          Wildcard app_*
          Nest_under app
          Remove_prefix app_
    
    logLevel: info

