fluent-bit:
  image:
    repository: cr.fluentbit.io/fluent/fluent-bit
    pullPolicy: Always
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      memory: 60Mi
  serviceMonitor:
    enabled: true
  dashboards:
    enabled: true
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level {{ .Values.logLevel }}
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          storage.path              /var/log/ds/flb-storage/
          storage.sync              normal
          storage.checksum          off
          storage.backlog.mem_limit 60M

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          Parser docker
          # multiline.parser docker, cri
          Tag kube.*
          DB /var/log/ds/flb_kube.db
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On
    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Merge_Log_Key log_json
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

    ## https://docs.fluentbit.io/manual/pipeline/filters
    # filters: |
    #   [FILTER]
    #       Name kubernetes
    #       Match *
    #       Merge_Log On
    #       Keep_Log Off
    #       K8S-Logging.Parser On
    #       K8S-Logging.Exclude On
    #   [FILTER]
    #       Name     grep
    #       Match    *
    #       Exclude  log \"GET \/ HTTP\/1\.1\" 200
    #   [FILTER]
    #       Name        parser
    #       Match       nginx.*
    #       Key_Name    log
    #       Parser      nginx
    #       Preserve_Key  True
    #       Reserve_Data  True
    #   [FILTER]
    #       Name modify
    #       Match nginx.*
    #       Remove stream
    #       Rename method app_method
    #       Rename path app_path
    #       Rename remote app_remote
    #       Rename size app_size
    #       Rename host app_host
    #       Rename user app_user
    #       Rename code app_code
    #       Rename referer app_referer
    #   [FILTER]
    #       Name nest
    #       Match nginx.*
    #       Operation nest
    #       Wildcard app_*
    #       Nest_under app
    #       Remove_prefix app_
    
    logLevel: info

