fluent-bit:
  config:
    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          name                   loki
          match                  kube.*
          host                   loki-headless
          port                   3100
          labels                 source=k8s-apps
          label_keys             $kubernetes['namespace_name'], $kubernetes['pod_name'], $kubernetes['container_name']
          line_format            json
      [OUTPUT]
          name                   loki
          match                  kube_events
          host                   loki-headless
          port                   3100
          labels                 source=k8s-events
