fluent-bit:
  config:
    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          name                   loki
          match                  *
          host                   loki-headless
          port                   3100
          labels                 job=fluentbit-k8s
          label_keys             level, kubernetes_namespace_name, kubernetes_pod_name, kubernetes_container_name
          line_format            json
