fluent-bit:
  env:
    # Note that for security reasons you should fetch the credentials through a Kubernetes Secret https://kubernetes.io/docs/concepts/configuration/secret/ . You may use the envFrom for this.
    - name: FLUENT_LOKI_URL
      value: http://loki-headless:3100/loki/api/v1/push
  config:
    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name            es
          Match           *
          Host            opensearch-dev.aepps.com
          Port            443
          AWS_Auth        On
          AWS_Region      eu-central-1
          tls             On
          Replace_Dots    On
          Index fluentbit
