fluent-bit:
  config:
    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          name                   loki
          match                  *
          host                   loki-headless
          port                   3100
          labels                 job=fluentbit-k8s
          label_keys             $kubernetes['namespace_name'], $kubernetes['pod_name'], $kubernetes['container_name']
          line_format            json
