---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-slack-config
  labels:
    alertmanagerConfig: {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: default-slack
    routes:
      - matchers:
        - name: service
          value: kube-prometheus-blackbox-exporter
          matchType: "="
        groupBy: ['job']
        receiver: apps-slack
      - matchers:
        - name: namespace
          value: kube-system|monitoring|tools|argocd
          matchType: "=~"
        receiver: platform-slack
      - matchers:
        - name: namespace
          value: aenodes
          matchType: "="
        receiver: blockchain-slack
      - matchers:
        - name: namespace
          value: apps
          matchType: "="
        receiver: apps-slack
  receivers:
    - name: default-slack
      slackConfigs:
        - sendResolved: true
          apiURL:
            name: kube-prometheus-stack-app-secrets
            key: SLACK_HOOK_URL
          channel: '#monitoring'
          title: {{`"{{ template \"slack.ae.title\" . }}"`}}
          text: {{`"{{ template \"slack.ae.text\" . }}"`}}
    {{- if .Values.alerts.platformSlackChannel }}
    - name: platform-slack
      slackConfigs:
        - sendResolved: true
          apiURL:
            name: kube-prometheus-stack-app-secrets
            key: {{ .Values.alerts.platformSlackHookUrlKey }}
          channel: {{ .Values.alerts.platformSlackChannel }}
          title: {{`"{{ template \"slack.ae.title\" . }}"`}}
          text: {{`"{{ template \"slack.ae.text\" . }}"`}}
    {{- end }}
    {{- if .Values.alerts.blockchainSlackChannel }}
    - name: blockchain-slack
      slackConfigs:
        - sendResolved: true
          apiURL:
            name: kube-prometheus-stack-app-secrets
            key: {{ .Values.alerts.blockchainSlackHookUrlKey }}
          channel: {{ .Values.alerts.blockchainSlackChannel }}
          title: {{`"{{ template \"slack.ae.title\" . }}"`}}
          text: {{`"{{ template \"slack.ae.text\" . }}"`}}
    {{- end }}
    {{- if .Values.alerts.appsSlackChannel }}
    - name: apps-slack
      slackConfigs:
        - sendResolved: true
          apiURL:
            name: kube-prometheus-stack-app-secrets
            key: {{ .Values.alerts.appsSlackHookUrlKey }}
          channel: {{ .Values.alerts.appsSlackChannel }}
          title: {{`"{{ template \"slack.ae.title\" . }}"`}}
          text: {{`"{{ template \"slack.ae.text\" . }}"`}}
    {{- end }}
