apiVersion: v2
name: cluster-autoscaler
description: Scales Kubernetes worker nodes within autoscaling groups

version: 9.37.0

dependencies:
  - name: cluster-autoscaler
    version: 9.37.0
    appVersion: 1.30.0
    repository: https://kubernetes.github.io/autoscaler
  - name: app-secrets
    version: 0.0.1
    repository: "file://../app-secrets"
