cluster-autoscaler:
  resources:
    limits:
      cpu: 75m
      memory: 96Mi
    requests:
      cpu: 50m
      memory: 96Mi
  cloudProvider: aws
  awsRegion: eu-central-1
  serviceMonitor:
    enabled: true
