cluster-autoscaler:
  resources:
    requests:
      cpu: 15m
      memory: 96Mi
    limits:
      memory: 96Mi
  cloudProvider: aws
  awsRegion: eu-central-1
  serviceMonitor:
    enabled: true
  extraArgs:
    balance-similar-node-groups: true
    scale-down-utilization-threshold: 0.8
    skip-nodes-with-local-storage: false
