cluster-autoscaler:
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      memory: 96Mi
  cloudProvider: aws
  awsRegion: eu-central-1
  serviceMonitor:
    enabled: true
  extraArgs:
    balance-similar-node-groups: true
