velero:
  configuration:
    backupStorageLocation:
      - name: s3
        provider: aws
        bucket: aeternity-velero-backup-stg
        default: true
        config:
          region: eu-central-1

  serviceAccount:
    server:
      annotations: 
        eks.amazonaws.com/role-arn: "arn:aws:iam::106102538874:role/velero-stg"
