apiVersion: v2
name: prometheus-blackbox-exporter
description: prometheus-blackbox-exporter

version: 5.3.1

dependencies:
  - name: prometheus-blackbox-exporter
    version: 5.3.1
    repository: https://prometheus-community.github.io/helm-charts
