prometheus-blackbox-exporter:
  serviceMonitor:
    targets:
      # Tools
      - name: argocd
        url: https://argocd.dev.aeternity.io
        additionalMetricsRelabels:
          scope: tools
      - name: grafana
        url: https://grafana.dev.aeternity.io
        additionalMetricsRelabels:
          scope: tools

      # Infrastructure/Core apps
      - name: base
        url: https://base.dev.aepps.com
        additionalMetricsRelabels:
          scope: core-apps
      - name: base-backend
        url: https://base-backend.dev.aepps.com/version
        additionalMetricsRelabels:
          scope: core-apps
      - name: contracts
        url: https://contracts.dev.aepps.com
        additionalMetricsRelabels:
          scope: core-apps
      - name: faucet
        url: https://faucet.dev.aepps.com
        additionalMetricsRelabels:
          scope: core-apps
      - name: repl
        url: https://repl.dev.aepps.com
        additionalMetricsRelabels:
          scope: core-apps
      - name: compiler
        url: https://compiler.dev.aepps.com/version
        additionalMetricsRelabels:
          scope: core-apps
      - name: compiler-v7
        url: https://v7.compiler.dev.aepps.com/version
        additionalMetricsRelabels:
          scope: core-apps
      - name: compiler-v6
        url: https://v6.compiler.dev.aepps.com/version
        additionalMetricsRelabels:
          scope: core-apps
      - name: mdw-explorer-mainnet
        url: https://mdw-explorer-mainnet.dev.aepps.com
        additionalMetricsRelabels:
          scope: core-apps
      - name: mdw-explorer-testnet
        url: https://mdw-explorer-testnet.dev.aepps.com
        additionalMetricsRelabels:
          scope: core-apps

      # Applications
      ## Hyperchains Demo
      - name: aehc-demo-base
        url: https://base-aehc-demo.dev.aepps.com
      - name: aehc-demo-faucet
        url: https://faucet-aehc-demo.dev.aepps.com
      - name: aehc-demo-ui
        url: https://hyperchain-aehc-demo.dev.aepps.com
      - name: aehc-demo-mdw-parent
        url: https://explorer-aehc-demo-parent.dev.aepps.com
      - name: aehc-demo-mdw
        url: https://explorer-aehc-demo.dev.aepps.com
      ## Governance
      - name: governance
        url: https://governance.dev.aepps.com
      - name: governance-mainnet
        url: https://governance-server-mainnet.dev.aepps.com/version
      - name: governance-testnet
        url: https://governance-server-testnet.dev.aepps.com/version
      ## Graffiti
      - name: aepp-graffiti
        url: https://aepp-graffiti.dev.aepps.com
      - name: graffiti-server
        url: https://graffiti-server.dev.aepps.com/health
