prometheus-blackbox-exporter:
  serviceMonitor:
    targets:
      # Environment specific
      - name: base-hc
        url: https://base-hc.dev.aepps.com
      - name: hc-ui
        url: https://hc-ui.dev.aepps.com

      # Tools
      - name: argocd
        url: https://argocd.dev.aeternity.io
      - name: prometheus
        url: https://prometheus.dev.aeternity.io
      - name: grafana
        url: https://grafana.dev.aeternity.io

      # Infrastructure
      - name: base
        url: https://base.dev.aepps.com
      - name: contracts
        url: https://contracts.dev.aepps.com
      - name: faucet
        url: https://faucet.dev.aepps.com
      - name: faucet-nodejs
        url: https://faucet-nodejs.dev.aepps.com
      - name: repl
        url: https://repl.dev.aepps.com
      - name: compiler
        url: https://compiler.dev.aepps.com/version
      - name: mdw-explorer-mainnet
        url: https://mdw-explorer-mainnet.dev.aepps.com
      - name: mdw-explorer-testnet
        url: https://mdw-explorer-testnet.dev.aepps.com

      # Applications
      ## Aescan
      - name: aescan
        url: https://aescan.dev.aepps.com
      - name: aescan-testnet
        url: https://aescan-testnet.dev.aepps.com
      ## Governance
      - name: governance
        url: https://governance.dev.aepps.com
      - name: governance-mainnet
        url: https://governance-server-mainnet.dev.aepps.com/version
      - name: governance-testnet
        url: https://governance-server-testnet.dev.aepps.com/version
      ## Grafitti
      - name: aepp-grafitti
        url: https://aepp-grafitti.dev.aepps.com
      # - name: aepp-grafitti-mainnet
      #   url: https://graffiti-server-mainnet.dev.aepps.com/health
      # - name: aepp-grafitti-testnet
      #   url: https://graffiti-server-testnet.dev.aepps.com/health
      ## DEX
      - name: dex
        url: https://dex.dev.aepps.com
      - name: dex-backend-mainnet
        url: https://dex-backend-mainnet.dev.aepps.com
      - name: dex-backend-testnet
        url: https://dex-backend-testnet.dev.aepps.com
      ## GA Multisignature
      - name: ga-multisig-ui
        url: https://ga-multisig-ui.dev.aepps.com
      - name: ga-multisig-backend
        url: https://ga-multisig-backend.dev.aepps.com
      ## State Channel Demo
      - name: state-channel-demo
        url: https://state-channel-demo.dev.aepps.com
      - name: state-channel-demo-backend
        url: https://state-channel-demo-backend.dev.aepps.com
      - name: develop-state-channel-demo
        url: https://develop-state-channel-demo.dev.aepps.com
      - name: develop-state-channel-demo-backend
        url: https://develop-state-channel-demo-backend.dev.aepps.com
      ## Superhero
      - name: superhero
        url: https://superhero.dev.aepps.com
      - name: superhero-backend
        url: https://superhero-backend.dev.aepps.com/health/backend
        module: http_backend
      - name: superhero-wallet
        url: https://superhero-wallet.dev.aepps.com
