prometheus-blackbox-exporter:
  serviceMonitor:
    targets:
      # Tools
      - name: argocd
        url: https://argocd.prd.aeternity.io
        additionalMetricsRelabels:
          job: tools
      - name: grafana
        url: https://grafana.prd.aeternity.io
        additionalMetricsRelabels:
          job: tools

      # Infrastructure/Core apps
      - name: base
        url: https://base.aepps.com
        additionalMetricsRelabels:
          job: core-apps
      - name: base-backend
        url: https://base-backend.prd.aepps.com/version
        additionalMetricsRelabels:
          job: core-apps
      - name: contracts
        url: https://contracts.aepps.com
        additionalMetricsRelabels:
          job: core-apps
      - name: faucet
        url: https://faucet.aepps.com
        additionalMetricsRelabels:
          job: core-apps
      - name: repl
        url: https://repl.prd.aepps.com
        additionalMetricsRelabels:
          job: core-apps
      - name: compiler-v8
        url: https://v8.compiler.aepps.com/version
        additionalMetricsRelabels:
          job: core-apps
      - name: mainnet-mdw
        url: https://mainnet.aeternity.io/mdw/status
        module: http_mdw_match
        additionalMetricsRelabels:
          job: core-apps
