prometheus-blackbox-exporter:
  pspEnabled: false
  resources:
    requests:
      cpu: 30m
      memory: 16Mi
    limits:
      memory: 24Mi

  config:
    modules:
      http_2xx:
        prober: http
        timeout: 15s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"

  serviceMonitor:
    enabled: true
    defaults:
      additionalMetricsRelabels:
          namespace: apps
      additionalRelabeling: []
      labels: {}
      interval: 60s
      scrapeTimeout: 60s
      module: http_2xx
