prometheus-blackbox-exporter:
  serviceMonitor:
    targets:
      # Environment specific
      - name: base-hc
        url: https://base-hc.dev.aepps.com
      - name: hc-ui
        url: https://hc-ui.dev.aepps.com

      # Tools
      - name: argocd
        url: https://argocd.dev.aeternity.io
        additionalMetricsRelabels:
          job: tools
      - name: prometheus
        url: https://prometheus.dev.aeternity.io
        additionalMetricsRelabels:
          job: tools
      - name: grafana
        url: https://grafana.dev.aeternity.io
        additionalMetricsRelabels:
          job: tools

      # Infrastructure/Core apps
      - name: base
        url: https://base.dev.aepps.com
        additionalMetricsRelabels:
          job: core-apps
      - name: contracts
        url: https://contracts.dev.aepps.com
        additionalMetricsRelabels:
          job: core-apps
      - name: faucet
        url: https://faucet.dev.aepps.com
        additionalMetricsRelabels:
          job: core-apps
      - name: repl
        url: https://repl.dev.aepps.com
        additionalMetricsRelabels:
          job: core-apps
      - name: compiler
        url: https://compiler.dev.aepps.com/version
        additionalMetricsRelabels:
          job: core-apps
      - name: mdw-explorer-mainnet
        url: https://mdw-explorer-mainnet.dev.aepps.com
        additionalMetricsRelabels:
          job: core-apps
      - name: mdw-explorer-testnet
        url: https://mdw-explorer-testnet.dev.aepps.com
        additionalMetricsRelabels:
          job: core-apps

      # Applications
      ## Governance
      - name: governance
        url: https://governance.dev.aepps.com
      - name: governance-mainnet
        url: https://governance-server-mainnet.dev.aepps.com/version
      - name: governance-testnet
        url: https://governance-server-testnet.dev.aepps.com/version
      ## Grafitti
      - name: aepp-grafitti
        url: https://aepp-grafitti.dev.aepps.com
      - name: aepp-grafitti
        url: https://graffiti-server.dev.aepps.com/health
      ## State Channel Demo
      - name: state-channel-demo
        url: https://state-channel-demo.dev.aepps.com
      - name: state-channel-demo-backend
        url: https://state-channel-demo-backend.dev.aepps.com
      - name: develop-state-channel-demo
        url: https://develop-state-channel-demo.dev.aepps.com
      - name: develop-state-channel-demo-backend
        url: https://develop-state-channel-demo-backend.dev.aepps.com
