prometheus-blackbox-exporter:
  serviceMonitor:
    targets:
      # Environment specific
      - name: base-hc
        url: https://base-hc.dev.aepps.com
      - name: hc-ui
        url: https://hc-ui.dev.aepps.com

      # Tools
      - name: argocd
        url: https://argocd.dev.aeternity.io
      - name: prometheus
        url: https://prometheus.dev.aeternity.io
      - name: grafana
        url: https://grafana.dev.aeternity.io

      # Infrastructure
      - name: base
        url: https://base.dev.aepps.com
      - name: contracts
        url: https://contracts.dev.aepps.com
      - name: faucet
        url: https://faucet.dev.aepps.com
      - name: faucet-nodejs
        url: https://faucet-nodejs.dev.aepps.com
      - name: repl
        url: https://repl.dev.aepps.com
      - name: compiler
        url: https://compiler.dev.aepps.com/version
      - name: mdw-explorer-mainnet
        url: https://mdw-explorer-mainnet.dev.aepps.com
      - name: mdw-explorer-testnet
        url: https://mdw-explorer-testnet.dev.aepps.com
