prometheus-blackbox-exporter:
  resources:
    requests:
      cpu: 10m
  serviceMonitor:
    targets:
      # Tools
      - name: argocd
        url: https://argocd.dev.aeternity.io
        additionalMetricsRelabels:
          namespace: tools
      - name: grafana
        url: https://grafana.dev.aeternity.io
        additionalMetricsRelabels:
          namespace: tools

      # Infrastructure/Core apps
      - name: base
        url: https://base.dev.aepps.com
      - name: base-backend
        url: https://base-backend.dev.aepps.com/version
      - name: contracts
        url: https://contracts.dev.aepps.com
      - name: faucet
        url: https://faucet.dev.aepps.com
      - name: repl
        url: https://repl.dev.aepps.com
      - name: compiler
        url: https://compiler.dev.aepps.com/version
      - name: compiler-v7
        url: https://v7.compiler.dev.aepps.com/version
      - name: compiler-v6
        url: https://v6.compiler.dev.aepps.com/version
      - name: mdw-explorer-mainnet
        url: https://mdw-explorer-mainnet.dev.aepps.com
      - name: mdw-explorer-testnet
        url: https://mdw-explorer-testnet.dev.aepps.com

      # Applications
      ## Hyperchains Demo
      - name: aehc-demo-base
        url: https://base-aehc-demo.dev.aepps.com
      # - name: aehc-demo-faucet
      #   url: https://faucet-aehc-demo.dev.aepps.com
      - name: aehc-demo-ui
        url: https://hyperchain-aehc-demo.dev.aepps.com
      - name: aehc-demo-mdw-parent
        url: https://explorer-aehc-demo-parent.dev.aepps.com
      - name: aehc-demo-mdw
        url: https://explorer-aehc-demo.dev.aepps.com
      ## Governance
      - name: governance
        url: https://governance.dev.aepps.com
      - name: governance-mainnet
        url: https://governance-server-mainnet.dev.aepps.com/version
      - name: governance-testnet
        url: https://governance-server-testnet.dev.aepps.com/version
      ## Graffiti
      - name: aepp-graffiti
        url: https://aepp-graffiti.dev.aepps.com
      - name: graffiti-server
        url: https://graffiti-server-testnet.dev.aepps.com/health
