app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7
    values:
      DB_PASS: "/wikijs/WIKI_DB_PASSWORD"

wikijs:
  image:
    repository: ghcr.io/linuxserver/wikijs
    tag: version-2.5.201
    pullPolicy: IfNotPresent
  # -- environment variables. See [image docs](https://docs.linuxserver.io/images/docker-wikijs#environment-variables-e) for more details.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: UTC
    DB_TYPE: "postgres"
    DB_HOST: "postgresql.wikijs.svc.cluster.local"
    DB_PORT: "5432"
    DB_USER: "wikijs"
    # DB_PASS -- Password to connect to the database
    DB_NAME: "wikijs"
  envFrom:
   - secretRef:
       name: wikijs-app-secrets
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: "wikijs.dev.aeternity.io"
          paths:
          - path: /

  persistence:
    config:
      enabled: false
    data:
      enabled: false
      mountPath: /app/wiki/data
