apiVersion: v2
name: hedgedoc
description: hedgedoc chart

version: 0.4.0

dependencies:
  - name: app
    version: 0.4.0
    repository: "file://../app"
  - name: app-secrets
    version: 0.0.1
    repository: "file://../app-secrets"
