app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7
    values:
      DB_PASS: "/hedgedoc/HEDGEDOC_DB_PASSWORD"
      CMD_GITHUB_CLIENTID: "/hedgedoc/GITHUB_CLIENT_ID"
      CMD_GITHUB_CLIENTSECRET: "/hedgedoc/GITHUB_CLIENT_SECRET"
      SESSION_SECRET: "/hedgedoc/SESSION_SECRET"

app:
  image:
    repository: ghcr.io/linuxserver/hedgedoc
    pullPolicy: IfNotPresent
    tag: "version-1.9.6"

  serviceMonitor:
    enabled: false

  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false

  service:
    port: 3000

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "hedgedoc2.dev.aeternity.io"
        paths:
          - path: "/"
        version: "version-1.9.6"
    versions:
    - {version: "version-1.9.6", gitSha: "12345"}

  env:
    CMD_DOMAIN: "hedgedoc2.dev.aeternity.io"
    DB_USER: hedgedoc
    DB_NAME: hedgedoc
    DB_HOST: "postgresql-hedgedoc.hedgedoc-2.svc.cluster.local"
    DB_PORT: "5432"
    CMD_LOGLEVEL: debug