app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7
    values:
      DB_PASS: "/hedgedoc/DB_PASSWORD"
      GITHUB_CLIENT_SECRET: "/hedgedoc/GITHUB_CLIENT_SECRET"
      GITHUB_CLIENT_ID: "/hedgedoc/GITHUB_CLIENT_ID"
      SESSION_SECRET: "/hedgedoc/SESSION_SECRET"

app:
  image:
    repository: ghcr.io/linuxserver/hedgedoc
    pullPolicy: IfNotPresent
    tag: "version-1.9.6"

  serviceMonitor:
    enabled: false

  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false

  service:
    port: 3000

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "hedgedoc2.dev.aepps.com"
        paths:
          - path: "/"
  env:
    CMD_DOMAIN: "hedgedoc.dev.aeternity.io"
    DB_USER: hedgedoc
    DB_NAME: hedgedoc
