app-secrets:
  external:
    remotePrefix: /k8s/dev-wgt7
    values:
      CMD_DB_PASSWORD: "/hedgedoc/HEDGEDOC_DB_PASSWORD"
      GITHUB_CLIENT_SECRET: "/hedgedoc/GITHUB_CLIENT_SECRET"
      GITHUB_CLIENT_ID: "/hedgedoc/GITHUB_CLIENT_ID"
      SESSION_SECRET: "/hedgedoc/SESSION_SECRET"

app:
  image:
    repository: "linuxserver/hedgedoc"
    tag: "1.9.4"
    pullPolicy: IfNotPresent
  service:
    port: 3000
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "hedgedoc.dev.aepps.com"
        paths:
          - path: "/"
    tls:
      - hosts:
        - "hedgedoc.dev.aepps.com"
        secretName: hedgedoc-cert
  secrets:
    external:
      values:
        CMD_DB_PASSWORD: "/k8s/dev-wgt7/hedgedoc/HEDGEDOC_DB_PASSWORD"
  env:
    CMD_DOMAIN: "hedgedoc2.dev.aeternity.io"
    DB_USER: hedgedoc
    DB_NAME: hedgedoc
    DB_HOST: "postgresql-hedgedoc.hedgedoc-2.svc.cluster.local"
    DB_PORT: "5432"
    CMD_LOGLEVEL: debug
  serviceMonitor:
    enabled: false
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false  
