---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.encValues }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
---
kind: ClusterRole
apiVersion:  rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}-secret-role
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["get", "patch", "delete", "create"]
---
kind: ClusterRoleBinding
apiVersion:  rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}-secret-role
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubernetes-event-exporter.fullname" . }}-secret-role
subjects:
  - kind: ServiceAccount
    name: {{ include "kubernetes-event-exporter.fullname" . }}
    namespace: {{ .Release.Namespace }}
