{{- if .Values.velero.enabled -}}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "rocketchat.fullname" . }}-backup
  namespace: "velero"
  labels:
    {{- include "rocketchat.labels" . | nindent 4 }}  
    velero.io/storage-location: {{ $.Values.velero.storageLocation }}
spec:
  schedule: {{ $.Values.velero.schedule | quote }}
  template:
    includedNamespaces:
        - {{ $.Release.Namespace | quote }}
    includedResources:
        {{- range $.Values.velero.includedResources }}
        - {{ . | quote}}
        {{- end }}
    storageLocation: {{ $.Values.velero.storageLocation }}
    ttl: {{ $.Values.velero.ttl }}
{{- end }}
