dnsSolverDomains:
  - 'aeternity.io'
  - 'aepps.com'
cert-manager:
  installCRDs: true
  resources:
    limits:
      cpu: 15m
      memory: 56Mi
    requests:
      cpu: 10m
      memory: 56Mi
  securityContext:
    fsGroup: 1001

  webhook:
    resources:
      limits:
        cpu: 15m
        memory: 24Mi
      requests:
        cpu: 10m
        memory: 24Mi

  cainjector:
    resources:
      limits:
        cpu: 15m
        memory: 164Mi
      requests:
        cpu: 10m
        memory: 164Mi
