dnsSolverDomains:
  - 'aeternity.io'
  - 'aepps.com'
cert-manager:
  installCRDs: true
  extraArgs:
    - --acme-http01-solver-resource-request-cpu=70m
    - --acme-http01-solver-resource-limits-cpu=100m
    - --acme-http01-solver-resource-request-memory=64Mi
    - --acme-http01-solver-resource-limits-memory=64Mi
  resources:
    requests:
      cpu: 50m
      memory: 56Mi
    limits:
      cpu: 75m
      memory: 56Mi
  securityContext:
    fsGroup: 1001

  webhook:
    resources:
      limits:
        memory: 24Mi
      requests:
        cpu: 10m
        memory: 24Mi

  cainjector:
    resources:
      limits:
        memory: 164Mi
      requests:
        cpu: 10m
        memory: 164Mi
