dnsSolverDomains:
  - 'aeternity.io'
  - 'aepps.com'
cert-manager:
  installCRDs: true
  resources:
    requests:
      cpu: 50m
      memory: 56Mi
    limits:
      cpu: 75m
      memory: 56Mi
  securityContext:
    fsGroup: 1001

  webhook:
    resources:
      limits:
        memory: 24Mi
      requests:
        cpu: 10m
        memory: 24Mi

  cainjector:
    resources:
      limits:
        memory: 164Mi
      requests:
        cpu: 10m
        memory: 164Mi
