redis:
  architecture: standalone
  persistence:
    enabled: false
  auth:
    enabled: false
  master:
    resources:
      limits:
        cpu: 15m
        memory: 12Mi
      requests:
        cpu: 10m
        memory: 12Mi
    persistence:
      enabled: false
  replica:
    resources:
      limits:
        cpu: 15m
        memory: 12Mi
      requests:
        cpu: 10m
        memory: 12Mi
