{{- if and (.Capabilities.APIVersions.Has "external-secrets.io/v1beta1") .Values.secrets.external.values -}}
{{- $prefix := .Values.secrets.external.remotePrefix }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: awssm
    kind: ClusterSecretStore
  target:
    {{- if .Values.secrets.external.secretName }}
    name: {{ .Values.secrets.external.secretName }}
    {{- else }}
    name: {{ include "app.fullname" . }}-external-secrets
    {{- end }}
    creationPolicy: Owner
  data:
  {{- range $key, $value := .Values.secrets.external.values }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $prefix }}{{ $value }}
  {{- end }}
{{- end -}}
