{{- if .Values.persistence.enabled }}
{{ $versions := .Values.versions }}
{{ $allVersions := append $versions (merge (dict "version" (default .Values.image.tag .Chart.AppVersion )) $) | compact | uniq }}
{{- range $key, $val := $allVersions}}
{{- if $val.version }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "app.versionedFullname" (merge (dict "version" $val.version) $) }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    app.kubernetes.io/version: {{ $val.version }}
  annotations:
  {{- if $.Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ $.Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ $.Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size | quote }}
{{- end }}
{{- end }}
{{- end }}
